import React from 'react';
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import { useFocusEffect } from '@react-navigation/native';
import { Screen } from '../../components/Screen';
import { Card } from '../../components/Card';
import { getThemeColors, radius, spacing, typography } from '../../design/tokens';
import { useAppContext } from '../../state/AppContext';
import { getNutritionExperience, getNutritionPattern, logNutritionEvent, logWater, NutritionExperience } from '../../services/nutritionExperienceService';

const money = (value: number | null) => value == null ? 'Unavailable' : `${Math.round(value)}`;
const reasonCopy: Record<string, string> = { HIGHER_PROTEIN: 'Higher protein', HIGHER_FIBRE: 'Higher fibre', LOWER_FAT: 'Lower fat', CALORIE_FIT: 'Fits remaining calories', BALANCED_OPTION: 'Balanced option' };

export const NutritionExperienceScreen = () => {
  const { themeMode } = useAppContext();
  const palette = getThemeColors(themeMode);
  const [data, setData] = React.useState<NutritionExperience | null>(null);
  const [pattern, setPattern] = React.useState<Awaited<ReturnType<typeof getNutritionPattern>> | null>(null);
  const [tab, setTab] = React.useState<'today' | 'pattern'>('today');
  const [busy, setBusy] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);
  const [selectedMeal, setSelectedMeal] = React.useState<NutritionExperience['meals'][number] | null>(null);
  const refresh = React.useCallback(async () => { setError(null); try { const next = await getNutritionExperience(); setData(next); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load Nutrition.'); } }, []);
  useFocusEffect(React.useCallback(() => { void refresh(); }, [refresh]));

  const updateMeal = async (meal: NutritionExperience['meals'][number], state: 'CONSUMED_APPROVED' | 'SKIPPED', option = meal.options[0]) => {
    if (!data) return; setBusy(true);
    try { const next = await logNutritionEvent({ planId: data.plan.id, versionId: data.version.id, mealKey: meal.key, state, optionId: option?.id ?? null, mealName: option?.meal ?? null }); setData(next); setSelectedMeal(null); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to update this meal.'); } finally { setBusy(false); }
  };

  if (!data && !error) return <Screen contentStyle={styles.center}><ActivityIndicator color={palette.blue} /></Screen>;
  if (error && !data) return <Screen contentStyle={styles.screen}><Text style={[styles.title, { color: palette.textPrimary }]}>Nutrition</Text><Card style={{ backgroundColor: palette.card, borderColor: palette.stroke }}><Text style={[styles.body, { color: palette.textSecondary }]}>{error}</Text><Pressable onPress={() => void refresh()}><Text style={[styles.link, { color: palette.blue }]}>Try again</Text></Pressable></Card></Screen>;
  if (!data) return null;
  const target = data.version.content.dailyTargets;
  return <Screen scroll contentStyle={styles.screen}>
    <View style={styles.header}><View><Text style={[styles.eyebrow, { color: palette.textMuted }]}>Personalised diet plan</Text><Text style={[styles.title, { color: palette.textPrimary }]}>Nutrition</Text><Text style={[styles.date, { color: palette.textMuted }]}>Today, {new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short' })}</Text></View><View style={[styles.iconButton, { backgroundColor: palette.cardMuted, borderColor: palette.stroke }]}><Ionicons name="notifications-outline" size={22} color={palette.textPrimary} /></View></View>
    <View style={[styles.segment, { backgroundColor: palette.cardMuted }]}><Pressable onPress={() => setTab('today')} style={[styles.segmentItem, tab === 'today' && { backgroundColor: palette.surfaceAccent }]}><Text style={[styles.segmentText, { color: palette.textPrimary }]}>Today's Plan</Text></Pressable><Pressable onPress={async () => { setTab('pattern'); if (!pattern) setPattern(await getNutritionPattern()); }} style={[styles.segmentItem, tab === 'pattern' && { backgroundColor: palette.surfaceAccent }]}><Text style={[styles.segmentText, { color: palette.textPrimary }]}>My Pattern</Text></Pressable></View>
    {tab === 'pattern' ? <Pattern pattern={pattern} palette={palette} /> : <>
      <Card style={[styles.summary, { backgroundColor: palette.card, borderColor: palette.stroke }]}><Text style={[styles.section, { color: palette.textPrimary }]}>Today's Nutrition</Text><View style={styles.summaryRow}><View><Text style={[styles.bigNumber, { color: palette.textPrimary }]}>{money(data.totals.calories)}</Text><Text style={[styles.body, { color: palette.textMuted }]}>of {target.calories == null ? 'unavailable' : `${target.calories} kcal`}</Text></View><Text style={[styles.remaining, { color: palette.blue }]}>{data.remaining.calories == null ? 'Target unavailable' : `${money(data.remaining.calories)} remaining`}</Text></View><View style={styles.macroRow}>{[['Protein', data.totals.protein, target.protein], ['Carbs', data.totals.carbs, null], ['Fat', data.totals.fat, null], ['Fibre', data.totals.fibre, null]].map(([label, value, planned]) => <View key={String(label)} style={[styles.macro, { backgroundColor: palette.cardMuted }]}><Text style={[styles.macroValue, { color: palette.textPrimary }]}>{money(Number(value))}</Text><Text style={[styles.caption, { color: palette.textMuted }]}>{label} {planned == null ? '' : `/ ${planned}g`}</Text></View>)}</View></Card>
      <View style={styles.twoCol}><Card style={[styles.smallCard, { backgroundColor: palette.card, borderColor: palette.stroke }]}><Text style={[styles.cardLabel, { color: palette.textMuted }]}>WATER</Text><Text style={[styles.cardValue, { color: palette.textPrimary }]}>{data.water.litres.toFixed(1)} <Text style={styles.unit}>/ {data.water.targetLitres == null ? '?' : data.water.targetLitres} L</Text></Text><Pressable onPress={async () => { setBusy(true); try { setData(await logWater({ planId: data.plan.id, versionId: data.version.id, litres: 0.25 })); } finally { setBusy(false); } }}><Text style={[styles.link, { color: palette.blue }]}>+ Add water</Text></Pressable></Card><Card style={[styles.smallCard, { backgroundColor: palette.card, borderColor: palette.stroke }]}><Text style={[styles.cardLabel, { color: palette.textMuted }]}>MEALS LOGGED</Text><Text style={[styles.cardValue, { color: palette.textPrimary }]}>{data.mealsFollowed} <Text style={styles.unit}>of {data.mealCount}</Text></Text><Text style={[styles.caption, { color: palette.textMuted }]}>{data.outOfPlanCount} out of plan · {data.skippedCount} skipped</Text></Card></View>
      {data.consultantNote ? <Card style={[styles.note, { backgroundColor: palette.blueSoft, borderColor: palette.blue }]}><Text style={[styles.section, { color: palette.textPrimary }]}>From your consultant</Text><Text style={[styles.body, { color: palette.textSecondary }]}>{data.consultantNote}</Text></Card> : null}
      <Text style={[styles.section, { color: palette.textPrimary }]}>Today's Meals</Text>
      {data.meals.map((meal) => <MealCard key={meal.key} meal={meal} palette={palette} disabled={busy} onConsume={() => setSelectedMeal(meal)} onSkip={() => void updateMeal(meal, 'SKIPPED')} />)}
      <Modal visible={selectedMeal != null} transparent animationType="slide" onRequestClose={() => setSelectedMeal(null)}>
        <View style={styles.modalBackdrop}><View style={[styles.modal, { backgroundColor: palette.card, borderColor: palette.stroke }]}>
          <Text style={[styles.section, { color: palette.textPrimary }]}>Choose your {selectedMeal?.label}</Text>
          <Text style={[styles.body, { color: palette.textMuted }]}>All options are approved by your consultant.</Text>
          <ScrollView contentContainerStyle={styles.modalOptions}>{selectedMeal?.options.map((option) => <Pressable key={`${selectedMeal.key}-${option.id ?? option.slot}`} disabled={busy} onPress={() => void updateMeal(selectedMeal, 'CONSUMED_APPROVED', option)} style={[styles.optionChoice, { backgroundColor: palette.cardMuted, borderColor: palette.stroke }]}><Text style={[styles.option, { color: palette.textPrimary }]}>{option.meal}</Text><Text style={[styles.body, { color: palette.textMuted }]}>{option.portion} · {option.approxKcal ?? '—'} kcal · P {option.proteinGrams ?? '—'}g</Text><Text style={[styles.caption, { color: palette.success }]}>{(option.rankingReasons ?? []).slice(0, 2).map((reason) => reasonCopy[reason] ?? reason).join(' · ')}</Text></Pressable>)}</ScrollView>
          <Pressable onPress={() => setSelectedMeal(null)} style={[styles.action, { backgroundColor: palette.cardMuted }]}><Text style={[styles.actionText, { color: palette.textPrimary }]}>Cancel</Text></Pressable>
        </View></View>
      </Modal>
    </>}
  </Screen>;
};

const MealCard = ({ meal, palette, disabled, onConsume, onSkip }: { meal: NutritionExperience['meals'][number]; palette: ReturnType<typeof getThemeColors>; disabled: boolean; onConsume: () => void; onSkip: () => void }) => <Card style={[styles.mealCard, { backgroundColor: palette.card, borderColor: palette.stroke }]}><View style={styles.mealHeader}><View><Text style={[styles.mealTitle, { color: palette.textPrimary }]}>{meal.label}</Text><Text style={[styles.body, { color: palette.textMuted }]}>{meal.window} · {meal.options.length} approved option{meal.options.length === 1 ? '' : 's'}</Text></View><Text style={[styles.status, { color: meal.state === 'CONSUMED_APPROVED' ? palette.success : palette.textMuted }]}>{meal.state === 'PENDING' ? 'Pending' : meal.state === 'SKIPPED' ? 'Skipped' : meal.state === 'CONSUMED_OUT_OF_PLAN' ? 'Out of plan' : 'Consumed'}</Text></View>{meal.options[0] ? <><Text style={[styles.option, { color: palette.textPrimary }]}>{meal.options[0].meal}</Text><Text style={[styles.body, { color: palette.textMuted }]}>{meal.options[0].approxKcal ?? '~'} kcal · P {meal.options[0].proteinGrams ?? '—'}g</Text><Text style={[styles.caption, { color: palette.blue }]}>{(meal.options[0].rankingReasons ?? []).slice(0, 2).map((reason) => reasonCopy[reason] ?? reason).join(' · ')}</Text></> : <Text style={[styles.body, { color: palette.textMuted }]}>No approved options provided.</Text>}<View style={styles.actions}>{meal.state === 'PENDING' ? <><Pressable disabled={disabled} onPress={onConsume} style={[styles.action, { backgroundColor: palette.blue }]}><Text style={styles.actionText}>Choose meal</Text></Pressable><Pressable disabled={disabled} onPress={onSkip} style={[styles.action, { backgroundColor: palette.cardMuted }]}><Text style={[styles.actionText, { color: palette.textPrimary }]}>Skip</Text></Pressable></> : <Text style={[styles.caption, { color: palette.textMuted }]}>Updated from your saved nutrition record</Text>}</View></Card>;

const Pattern = ({ pattern, palette }: { pattern: Awaited<ReturnType<typeof getNutritionPattern>> | null; palette: ReturnType<typeof getThemeColors> }) => pattern ? <><Text style={[styles.section, { color: palette.textPrimary }]}>My Nutrition Pattern</Text><Text style={[styles.body, { color: palette.textMuted }]}>Last 7 days</Text><View style={styles.twoCol}><Metric label="Plan adherence" value={pattern.planAdherencePercent == null ? '—' : `${pattern.planAdherencePercent}%`} palette={palette} /><Metric label="Out-of-plan meals" value={String(pattern.outOfPlanMeals)} palette={palette} /><Metric label="Skipped meals" value={String(pattern.skippedMeals)} palette={palette} /><Metric label="Water target days" value={pattern.waterTargetDays == null ? '—' : `${pattern.waterTargetDays}/7`} palette={palette} /></View><Card style={[styles.note, { backgroundColor: palette.card, borderColor: palette.stroke }]}>{pattern.insights.map((insight) => <Text key={insight} style={[styles.body, { color: palette.textSecondary }]}>· {insight}</Text>)}</Card></> : <ActivityIndicator color={palette.blue} />;
const Metric = ({ label, value, palette }: { label: string; value: string; palette: ReturnType<typeof getThemeColors> }) => <Card style={[styles.metric, { backgroundColor: palette.card, borderColor: palette.stroke }]}><Text style={[styles.caption, { color: palette.textMuted }]}>{label}</Text><Text style={[styles.cardValue, { color: palette.blue }]}>{value}</Text></Card>;

const styles = StyleSheet.create({ screen: { gap: spacing.md, paddingBottom: 120 }, center: { alignItems: 'center', justifyContent: 'center' }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, eyebrow: { ...typography.body }, title: { ...typography.titleXL, fontSize: 34 }, date: { ...typography.body }, iconButton: { width: 52, height: 52, borderRadius: 26, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, segment: { flexDirection: 'row', borderRadius: radius.md, padding: 4 }, segmentItem: { flex: 1, alignItems: 'center', paddingVertical: 12, borderRadius: radius.sm }, segmentText: { ...typography.bodyStrong }, summary: { gap: spacing.md }, section: { ...typography.section }, summaryRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end' }, bigNumber: { ...typography.titleXL, fontSize: 42 }, remaining: { ...typography.bodyStrong }, macroRow: { flexDirection: 'row', gap: spacing.xs }, macro: { flex: 1, padding: spacing.sm, borderRadius: radius.sm, alignItems: 'center' }, macroValue: { ...typography.bodyStrong, fontSize: 18 }, caption: { ...typography.caption }, body: { ...typography.body }, twoCol: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, smallCard: { flexBasis: '48%', flexGrow: 1, gap: spacing.sm }, cardLabel: { ...typography.caption, letterSpacing: 1 }, cardValue: { ...typography.title, fontSize: 28 }, unit: { ...typography.body, fontWeight: '400' }, link: { ...typography.bodyStrong }, note: { gap: spacing.xs }, mealCard: { gap: spacing.sm }, mealHeader: { flexDirection: 'row', justifyContent: 'space-between' }, mealTitle: { ...typography.section, fontSize: 20 }, status: { ...typography.bodyStrong }, option: { ...typography.bodyStrong, fontSize: 18 }, actions: { flexDirection: 'row', gap: spacing.sm, alignItems: 'center' }, action: { flex: 1, paddingVertical: 12, borderRadius: radius.pill, alignItems: 'center' }, actionText: { ...typography.bodyStrong, color: '#FFFFFF' }, metric: { flexBasis: '46%', flexGrow: 1, gap: spacing.sm }, modalBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.7)' }, modal: { maxHeight: '82%', borderTopLeftRadius: radius.lg, borderTopRightRadius: radius.lg, borderWidth: 1, padding: spacing.lg, gap: spacing.md }, modalOptions: { gap: spacing.sm }, optionChoice: { borderWidth: 1, borderRadius: radius.md, padding: spacing.md, gap: spacing.xs }
});
