import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Screen } from '../../components/Screen';
import { getThemeColors } from '../../design/tokens';
import { RootStackParamList } from '../../navigation/types';
import { formatPlanDuration, formatPlanPrice, getSubscriptionPlan, SubscriptionPlan } from '../../services/subscriptionService';
import { useAppContext } from '../../state/AppContext';

type Props = NativeStackScreenProps<RootStackParamList, 'SubscriptionCheckout'>;
export const SubscriptionCheckoutScreen = ({ navigation, route }: Props) => { const { themeMode } = useAppContext(); const palette = getThemeColors(themeMode); const [plan, setPlan] = useState<SubscriptionPlan | null>(null); useEffect(() => { void getSubscriptionPlan(route.params.planId).then((result) => setPlan(result.plan)); }, [route.params.planId]); return <Screen scroll contentStyle={styles.screen}><Pressable onPress={() => navigation.goBack()} style={styles.back}><Ionicons name="chevron-back" size={22} color={palette.textPrimary} /><Text style={[styles.backText, { color: palette.textPrimary }]}>Plan details</Text></Pressable><Text style={[styles.title, { color: palette.textPrimary }]}>Review your plan</Text>{plan ? <><View style={[styles.card, { borderColor: palette.stroke }]}><Text style={[styles.plan, { color: palette.textPrimary }]}>{plan.name}</Text><Text style={[styles.body, { color: palette.textSecondary }]}>{formatPlanDuration(plan.durationDays)} · {formatPlanPrice(plan)}</Text><View style={styles.line}><Text style={[styles.body, { color: palette.textSecondary }]}>Total payable</Text><Text style={[styles.total, { color: palette.textPrimary }]}>{formatPlanPrice(plan)}</Text></View></View><Text style={[styles.note, { color: palette.textSecondary }]}>Taxes, if applicable, will be shown at checkout.</Text><Text style={[styles.note, { color: palette.textSecondary }]}>Payment integration is coming in Phase 2. No payment has been initiated.</Text><Pressable onPress={() => navigation.navigate('SubscriptionPaymentPlaceholder')} style={styles.primary}><Text style={styles.primaryText}>Continue to Payment</Text></Pressable></> : <ActivityIndicator color="#B59CFF" />}</Screen>; };
const styles = StyleSheet.create({ screen: { gap: 16 }, back: { flexDirection: 'row', alignItems: 'center', gap: 4 }, backText: { fontFamily: 'Exo_600SemiBold', fontSize: 14 }, title: { fontFamily: 'Exo_700Bold', fontSize: 28 }, card: { borderWidth: 1, borderRadius: 18, padding: 18, gap: 10 }, plan: { fontFamily: 'Exo_700Bold', fontSize: 21 }, body: { fontFamily: 'Exo_400Regular', fontSize: 14, lineHeight: 20 }, line: { borderTopWidth: 1, borderTopColor: '#302B3C', paddingTop: 12, marginTop: 8, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, total: { fontFamily: 'Exo_700Bold', fontSize: 22 }, note: { fontFamily: 'Exo_400Regular', fontSize: 13, lineHeight: 19 }, primary: { minHeight: 48, borderRadius: 12, backgroundColor: '#6A4FB3', alignItems: 'center', justifyContent: 'center' }, primaryText: { color: '#FFFFFF', fontFamily: 'Exo_700Bold', fontSize: 15 } });
