import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Screen } from '../../components/Screen';
import { getThemeColors } from '../../design/tokens';
import { RootStackParamList } from '../../navigation/types';
import { formatPlanDuration, formatPlanPrice, getSubscriptionPlans, SubscriptionPlan } from '../../services/subscriptionService';
import { useAppContext } from '../../state/AppContext';

type Props = NativeStackScreenProps<RootStackParamList, 'SubscriptionCompare'>;
const features = [{ label: 'Health tracking', key: 'health_tracking' }, { label: 'Wearable sync', key: 'wearable_sync' }, { label: 'Medication tracking', key: 'medication_tracker' }, { label: 'Stress Test', key: 'stress_test' }, { label: 'Health reports', key: 'health_reports' }, { label: 'Progress tracking', key: 'progress_tracking' }];
export const SubscriptionCompareScreen = ({ navigation }: Props) => { const { themeMode } = useAppContext(); const palette = getThemeColors(themeMode); const [plans, setPlans] = useState<SubscriptionPlan[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { void getSubscriptionPlans().then((result) => setPlans(result.plans.filter((plan) => !plan.developmentOnly))).finally(() => setLoading(false)); }, []); return <Screen contentStyle={styles.screen}><Pressable onPress={() => navigation.goBack()} style={styles.back}><Ionicons name="chevron-back" size={22} color={palette.textPrimary} /><Text style={[styles.backText, { color: palette.textPrimary }]}>Plans</Text></Pressable><Text style={[styles.title, { color: palette.textPrimary }]}>Compare plans</Text><Text style={[styles.body, { color: palette.textSecondary }]}>Compare the capabilities included in each active plan.</Text>{loading ? <ActivityIndicator color="#B59CFF" /> : <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.compare}><View style={styles.labels}><View style={styles.headerCell} /><View style={styles.headerCell} /><View style={styles.headerCell} />{features.map((feature) => <View key={feature.key} style={styles.labelCell}><Text style={[styles.body, { color: palette.textSecondary }]}>{feature.label}</Text></View>)}</View>{plans.map((plan) => <View key={plan.id} style={[styles.column, { borderColor: plan.recommended ? '#8D72D8' : palette.stroke }]}><Text style={[styles.planName, { color: palette.textPrimary }]} numberOfLines={2}>{plan.name}</Text><Text style={styles.price}>{formatPlanPrice(plan)}</Text><Text style={[styles.meta, { color: palette.textSecondary }]}>{formatPlanDuration(plan.durationDays)}</Text>{features.map((feature) => <View key={feature.key} style={styles.cell}><Text style={styles.check}>{plan.entitlements.some((item) => item.toLowerCase() === feature.key) ? '✓' : '—'}</Text></View>)}</View>)}</ScrollView>}</Screen>; };
const styles = StyleSheet.create({ screen: { gap: 14 }, back: { flexDirection: 'row', alignItems: 'center', gap: 4 }, backText: { fontFamily: 'Exo_600SemiBold', fontSize: 14 }, title: { fontFamily: 'Exo_700Bold', fontSize: 27 }, body: { fontFamily: 'Exo_400Regular', fontSize: 14, lineHeight: 20 }, compare: { gap: 8, paddingVertical: 8 }, labels: { width: 142 }, column: { width: 156, borderWidth: 1, borderRadius: 14, padding: 10, gap: 0 }, headerCell: { height: 34, marginBottom: 6 }, labelCell: { minHeight: 48, justifyContent: 'center', borderBottomWidth: 1, borderBottomColor: '#2A2635' }, planName: { minHeight: 34, fontFamily: 'Exo_700Bold', fontSize: 13, lineHeight: 16 }, price: { color: '#B59CFF', fontFamily: 'Exo_700Bold', fontSize: 18, marginTop: 8 }, meta: { fontFamily: 'Exo_400Regular', fontSize: 12, marginBottom: 7 }, cell: { minHeight: 48, alignItems: 'center', justifyContent: 'center', borderBottomWidth: 1, borderBottomColor: '#2A2635' }, check: { color: '#B59CFF', fontFamily: 'Exo_700Bold', fontSize: 16 } });
