import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Linking, Modal, Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import { canonicalHealthStatus, canonicalHealthStatusLabel } from '@fiteatsy/health-intelligence';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Card } from '../../components/Card';
import { PageHeader } from '../../components/PageHeader';
import { PrimaryButton } from '../../components/PrimaryButton';
import { Screen } from '../../components/Screen';
import { getThemeColors, nutritionActionColors, radius, spacing, typography } from '../../design/tokens';
import type { RootStackParamList } from '../../navigation/types';
import { useCanonicalHealthSyncCoordinator, type HealthObservationDto } from '../../services/canonicalHealthSyncCoordinator';
import { useAppContext } from '../../state/AppContext';

type Props = NativeStackScreenProps<RootStackParamList, 'HealthDataSync'>;
const icons:Record<string,keyof typeof Ionicons.glyphMap>={steps:'footsteps-outline',distance:'navigate-outline',sleep:'moon-outline',heart_rate:'heart-outline',resting_heart_rate:'heart-circle-outline',hrv_sdnn:'pulse-outline',hrv_rmssd:'pulse-outline',active_energy:'flame-outline',exercise:'fitness-outline',workout:'barbell-outline',weight:'scale-outline',hydration:'water-outline',spo2:'water-outline',respiratory_rate:'cloud-outline'};
const metricColors:Record<string,string>={steps:'#FF5E1A',distance:'#0A84FF',sleep:'#5E5CE6',heart_rate:'#FF375F',resting_heart_rate:'#FF375F',hrv_sdnn:'#FF375F',hrv_rmssd:'#FF375F',active_energy:'#FF5E1A',exercise:'#32D74B',workout:'#FF5E1A',weight:'#BF5AF2',hydration:'#32D74B',spo2:'#64D2FF',respiratory_rate:'#64D2FF'};
const when=(iso?:string|null)=>{if(!iso)return'Not synced yet';const date=new Date(iso);if(Number.isNaN(date.getTime()))return'Not available';const minutes=Math.floor((Date.now()-date.getTime())/60000);return minutes<1?'Just now':minutes<60?`${minutes} min ago`:date.toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});};
const shown=(item:HealthObservationDto)=>item.metricType==='sleep_minutes'?{value:(item.value/60).toFixed(1),unit:'hr'}:{value:new Intl.NumberFormat().format(item.value),unit:item.unit};
const queryLabel=(state:string)=>canonicalHealthStatusLabel(state);

export const HealthDataSyncScreen=({navigation,route}:Props)=>{
  const {themeMode,onboarding,setOnboarding,setWearableSetupCompleted}=useAppContext();
  const palette=getThemeColors(themeMode);const health=useCanonicalHealthSyncCoordinator();
  const [selected,setSelected]=useState<HealthObservationDto|null>(null);const [permissionHelp,setPermissionHelp]=useState(false);const [syncPopupVisible,setSyncPopupVisible]=useState(false);const [syncRequested,setSyncRequested]=useState(false);
  const connected=health.providerState==='CONNECTED';const busy=health.metrics.some(metric=>metric.queryState==='QUERYING');
  const failed=health.uploadState==='ERROR'||health.providerState==='ERROR';const uploadPending=health.uploadState==='PENDING';
  const timedOutCount=health.metrics.filter(metric=>metric.queryState==='TIMEOUT').length;
  const readErrorCount=health.metrics.filter(metric=>metric.queryState==='ERROR').length;
  const terminalCount=health.metrics.filter(metric=>metric.queryState!=='IDLE'&&metric.queryState!=='QUERYING').length;
  const noDataCount=health.metrics.filter(metric=>metric.queryState==='NO_VISIBLE_DATA').length;
  const completedCount=Math.min(health.supportedMetricReadCount,terminalCount);
  const syncErrorMessage=health.message??(timedOutCount?`${timedOutCount} health ${timedOutCount===1?'metric took':'metrics took'} too long to respond.`:readErrorCount?`${readErrorCount} health ${readErrorCount===1?'metric could':'metrics could'} not be read.`:'Health data could not be synced. Check your connection and try again.');
  useEffect(()=>{if(busy)setSyncPopupVisible(true);else if(syncRequested&&(health.uploadState==='SYNCED'||failed||uploadPending))setSyncPopupVisible(true);},[busy,failed,health.uploadState,syncRequested,uploadPending]);
  const startSync=useCallback(()=>{setSyncRequested(true);setSyncPopupVisible(true);void health.syncLocalMetrics({trigger:'USER_CTA'});},[health]);
  const finishOnboarding=useCallback(()=>{setWearableSetupCompleted(true);if(onboarding)setOnboarding({...onboarding,wearablePreference:connected?'sync':'later'});navigation.reset({index:0,routes:[{name:'Main'}]});},[connected,navigation,onboarding,setOnboarding,setWearableSetupCompleted]);
  const reviewPermissions=useCallback(()=>{health.markPermissionReviewStarted();if(Platform.OS==='ios')setPermissionHelp(true);else void Linking.openSettings();},[health]);
  return <>
    <Screen scroll contentStyle={styles.content}>
      <PageHeader title="Health Data Sync" onBack={()=>navigation.goBack()}/>
      <Card style={styles.connectionCard}>
        <View style={styles.row}><View style={[styles.sourceIcon,{backgroundColor:palette.blueSoft}]}><Ionicons name={Platform.OS==='ios'?'heart':'fitness'} size={24} color={palette.blue}/></View><View style={styles.grow}><Text style={[styles.title,{color:palette.textPrimary}]}>{health.sourceName}</Text><Text style={[styles.body,{color:connected?palette.success:palette.warning}]}>{health.providerLabel}</Text></View><View style={[styles.chip,{backgroundColor:connected?palette.successSoft:palette.warningSoft}]}><Text style={[styles.chipText,{color:connected?palette.success:palette.warning}]}>{health.providerLabel}</Text></View></View>
        <View style={styles.summary}><View><Text style={[styles.caption,{color:palette.textMuted}]}>Last health read</Text><Text style={[styles.value,{color:palette.textPrimary}]}>{health.localHydrated?when(health.lifecycle.lastHealthReadAtISO):'Restoring saved data…'}</Text><Text style={[styles.caption,{color:palette.textMuted}]}>Saved on device {when(health.lifecycle.lastSavedAtISO)}</Text><Text style={[styles.caption,{color:palette.textMuted}]}>Uploaded {when(health.lifecycle.lastUploadedAtISO)}</Text></View><View><Text style={[styles.caption,{color:palette.textMuted}]}>Available metrics</Text><Text style={[styles.value,{color:palette.textPrimary}]}>{health.localHydrated?health.availableMetricCount:'—'}</Text></View></View>
        {!health.localHydrated?<View style={styles.hydrating}><Ionicons name="cloud-download-outline" size={22} color={palette.blue}/><Text style={[styles.body,{color:palette.textSecondary}]}>Restoring saved health data…</Text></View>:connected ? (
          <PrimaryButton title={busy ? 'Reading health data…' : 'Sync health data'} loading={busy} onPress={startSync} style={styles.syncButton} />
        ) : (
          <PrimaryButton title={`Connect ${health.sourceName}`} onPress={() => {setSyncRequested(true);setSyncPopupVisible(true);void health.requestAccess();}} style={styles.syncButton} />
        )}
        <PrimaryButton title="Review Permissions" variant="secondary" onPress={reviewPermissions}/>
        {connected&&!busy?<Text style={[styles.message,{color:palette.textSecondary}]}>Sync health data when you want to refresh your latest available information.</Text>:null}
        {health.pendingUploadCount>0?<Text style={[styles.message,{color:palette.warning}]}>{health.pendingUploadCount} {health.pendingUploadCount===1?'record':'records'} awaiting secure upload. Your health data remains available on this device.</Text>:null}
        {health.message?<Text accessibilityLiveRegion="polite" style={[styles.message,{color:palette.textSecondary}]}>{health.message}</Text>:null}
      </Card>
      <Text style={[styles.section,{color:palette.textPrimary}]}>Your Health Data</Text>
      {health.metrics.map(metric=>{const item=metric.observation;const display=item?shown(item):null;const label=queryLabel(metric.queryState);const status=canonicalHealthStatus(metric.queryState);const accent=metricColors[metric.definition.metricKey]??palette.blue;const dailyTotal=item?.sourceMetadata?.measurementMethod==='HEALTHKIT_DAILY_CUMULATIVE_STATISTIC';return <Pressable key={metric.definition.metricKey} disabled={!item} accessibilityRole="button" accessibilityLabel={`${metric.definition.displayName}, ${display?`${display.value} ${display.unit}`:label}`} onPress={()=>item&&setSelected(item)}><Card style={styles.metric}><View style={[styles.metricIcon,{backgroundColor:`${accent}1F`}]}><Ionicons name={icons[metric.definition.metricKey]??'analytics-outline'} size={22} color={accent}/></View><View style={styles.grow}><Text style={[styles.title,{color:accent}]}>{metric.definition.displayName}</Text>{display?<Text style={[styles.metricValue,{color:palette.textPrimary}]}>{display.value} <Text style={styles.metricUnit}>{display.unit}</Text></Text>:null}<Text style={[styles.caption,{color:palette.textMuted}]}>{item?`${dailyTotal?'Today total · ':''}${health.sourceName} · Updated ${when(item.measuredAtISO).toLowerCase()}`:`${health.sourceName} · ${label}`}</Text></View><Text style={[styles.chipText,{color:status==='AVAILABLE'?palette.success:palette.warning}]}>{label}</Text></Card></Pressable>;})}
      <Text style={[styles.section,{color:palette.textPrimary}]}>Sync Activity</Text>
      <Card>{health.activity.length?health.activity.map((item,index)=><View key={item.id} style={[styles.activity,index>0&&{borderTopColor:palette.stroke,borderTopWidth:1}]}><View style={styles.grow}><Text style={[styles.value,{color:palette.textPrimary}]}>{when(item.completedAtISO??item.startedAtISO)}</Text><Text style={[styles.caption,{color:palette.textMuted}]}>{item.metricsUpdated?`${item.metricsUpdated} records updated`:item.status==='RUNNING'?'Updating health data':'No visible health data found'}</Text></View><Text style={[styles.chipText,{color:item.status==='FAILED'?palette.danger:item.status==='PARTIAL'?palette.warning:palette.success}]}>{item.status}</Text></View>):<Text style={[styles.body,{color:palette.textSecondary}]}>Your recent sync activity will appear here.</Text>}</Card>
      {route.params?.entryContext==='ONBOARDING'?<View style={styles.onboarding}><PrimaryButton title={connected?'Continue':'Set Up Later'} onPress={finishOnboarding}/></View>:null}
    </Screen>
    <Modal visible={syncPopupVisible} transparent animationType="fade" statusBarTranslucent onRequestClose={()=>{if(!busy)setSyncPopupVisible(false);}}>
      <View style={[styles.syncOverlay,{backgroundColor:palette.overlay}]}>
        <View accessibilityRole="alert" accessibilityLiveRegion="assertive" style={[styles.syncDialog,{backgroundColor:palette.card,borderColor:palette.stroke}]}>
          {busy?<ActivityIndicator size="large" color={nutritionActionColors.primary}/>:<View style={[styles.syncResultIcon,{backgroundColor:health.uploadState==='SYNCED'?palette.successSoft:uploadPending?palette.warningSoft:palette.dangerSoft}]}><Ionicons name={health.uploadState==='SYNCED'?'checkmark-circle-outline':uploadPending?'cloud-offline-outline':'alert-circle-outline'} size={30} color={health.uploadState==='SYNCED'?palette.success:uploadPending?palette.warning:palette.danger}/></View>}
          <Text style={[styles.syncTitle,{color:palette.textPrimary}]}>{busy?'SYNCING HEALTH DATA':health.uploadState==='SYNCED'?'HEALTH DATA SYNCED':uploadPending?'SYNC INCOMPLETE':'PARTIALLY SYNCED'}</Text>
          <Text style={[styles.syncBody,{color:palette.textSecondary}]}>{busy?`Getting your latest available information from ${health.sourceName}.`:health.uploadState==='SYNCED'?noDataCount?`Your available health information is up to date. ${noDataCount} ${noDataCount===1?'metric has':'metrics have'} no recent data.`:'Your latest available health information has been updated.':uploadPending?`Your ${health.sourceName} values remain available on this device. Upload will resume when your connection returns.`:syncErrorMessage}</Text>
          <Text style={[styles.syncProgress,{color:palette.textMuted}]}>{busy?`${completedCount} OF ${health.supportedMetricReadCount} COMPLETED`:`${health.uploadState==='SYNCED'?health.supportedMetricReadCount:Math.max(0,health.supportedMetricReadCount-readErrorCount-timedOutCount)} OF ${health.supportedMetricReadCount} COMPLETED`}</Text>
          {!busy?<View style={styles.syncActions}>{health.uploadState!=='SYNCED'?<PrimaryButton title="Try again" onPress={startSync} style={styles.syncButton}/>:null}<PrimaryButton title="Done" variant="secondary" onPress={()=>setSyncPopupVisible(false)}/></View>:null}
        </View>
      </View>
    </Modal>
    <Modal visible={Boolean(selected)} transparent animationType="slide" onRequestClose={()=>setSelected(null)}><Pressable style={[styles.overlay,{backgroundColor:palette.overlay}]} onPress={()=>setSelected(null)}><Pressable style={[styles.sheet,{backgroundColor:palette.card}]} onPress={()=>undefined}>{selected?<><View style={styles.handle}/><Text style={[styles.section,{color:palette.textPrimary}]}>{health.metrics.find(metric=>metric.definition.backendCanonicalType===selected.metricType)?.definition.displayName??selected.metricType}</Text><Text style={[styles.detail,{color:palette.textPrimary}]}>{shown(selected).value} {shown(selected).unit}</Text><View style={styles.summary}><Text style={[styles.body,{color:palette.textMuted}]}>Last updated</Text><Text style={[styles.value,{color:palette.textPrimary}]}>{when(selected.measuredAtISO)}</Text></View><PrimaryButton title="Done" onPress={()=>setSelected(null)}/></>:null}</Pressable></Pressable></Modal>
    <Modal visible={permissionHelp} transparent animationType="slide" onRequestClose={()=>setPermissionHelp(false)}><Pressable style={[styles.overlay,{backgroundColor:palette.overlay}]} onPress={()=>setPermissionHelp(false)}><Pressable style={[styles.sheet,{backgroundColor:palette.card}]} onPress={()=>undefined}><View style={styles.handle}/><Text style={[styles.section,{color:palette.textPrimary}]}>Apple Health access</Text><Text style={[styles.body,{color:palette.textSecondary}]}>Review the health categories Fiteatsy may read. Returning to Fiteatsy refreshes local metrics once without reconnecting.</Text><PrimaryButton title="Request Health Access" onPress={()=>void health.requestAccess().then(()=>setPermissionHelp(false))}/><PrimaryButton title="Done" variant="secondary" onPress={()=>setPermissionHelp(false)}/></Pressable></Pressable></Modal>
  </>;
};

const styles=StyleSheet.create({content:{paddingBottom:spacing.xxl},connectionCard:{gap:spacing.md,marginTop:spacing.md},row:{flexDirection:'row',alignItems:'center',gap:spacing.sm},sourceIcon:{width:48,height:48,borderRadius:radius.md,alignItems:'center',justifyContent:'center'},grow:{flex:1},title:{...typography.cardTitle},body:{...typography.body},caption:{...typography.caption},chip:{paddingHorizontal:spacing.sm,paddingVertical:spacing.xs,borderRadius:radius.pill},chipText:{...typography.badge},summary:{flexDirection:'row',justifyContent:'space-between'},value:{...typography.bodyStrong},message:{...typography.bodySmall,textAlign:'center'},hydrating:{minHeight:48,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:spacing.sm},section:{...typography.sectionTitle,marginTop:spacing.xl,marginBottom:spacing.sm,textTransform:'uppercase'},metric:{flexDirection:'row',alignItems:'center',gap:spacing.sm,marginBottom:spacing.sm},metricIcon:{width:40,height:40,borderRadius:radius.md,alignItems:'center',justifyContent:'center'},metricValue:{...typography.metricSmall,marginVertical:2},metricUnit:{...typography.bodySmall},activity:{flexDirection:'row',alignItems:'center',paddingVertical:spacing.sm},onboarding:{marginTop:spacing.xl},overlay:{flex:1,justifyContent:'flex-end'},sheet:{borderTopLeftRadius:radius.lg,borderTopRightRadius:radius.lg,padding:spacing.xl,gap:spacing.md},handle:{width:44,height:4,borderRadius:2,backgroundColor:'#94A3B8',alignSelf:'center'},detail:{...typography.metric},syncOverlay:{flex:1,alignItems:'center',justifyContent:'center',padding:spacing.xl},syncDialog:{width:'100%',maxWidth:420,borderWidth:1,borderRadius:radius.lg,padding:spacing.xl,alignItems:'center',gap:spacing.md},syncResultIcon:{width:64,height:64,borderRadius:radius.pill,alignItems:'center',justifyContent:'center'},syncTitle:{...typography.sectionTitle,textTransform:'uppercase',textAlign:'center'},syncBody:{...typography.body,textAlign:'center'},syncProgress:{...typography.bodySmall,textAlign:'center'},syncActions:{alignSelf:'stretch',gap:spacing.sm,marginTop:spacing.xs},syncButton:{backgroundColor:nutritionActionColors.primary}});
