import crypto from 'node:crypto';
import { pool } from '../../db/pool.js';

export type GrievanceStatus='OPEN'|'IN_REVIEW'|'IN_PROGRESS'|'AWAITING_USER'|'RESOLVED'|'CLOSED';
export type GrievancePriority='LOW'|'NORMAL'|'HIGH'|'URGENT';
export type GrievanceInput={userId:string;clientId:string|null;clientRequestId:string;category:string;subject:string;description:string;contactPreference?:string|null;platform:string;appVersion?:string|null;buildNumber?:string|null;runtimeVersion?:string|null;osVersion?:string|null;deviceModel?:string|null;route?:string|null;networkType?:string|null;correlationId:string;attachment?:{contentType:string;bytes:Buffer}|null};

const select=`select g.*,u.name user_name,u.email_normalized user_email,a.name assigned_name
 from grievances g join users u on u.id=g.user_id left join users a on a.id=g.assigned_to`;
const map=(r:any)=>({id:r.id,referenceId:r.reference_id,userId:r.user_id,clientId:r.client_id,user:{name:r.user_name,email:r.user_email},category:r.category,subject:r.subject,description:r.description,contactPreference:r.contact_preference,status:r.status,priority:r.priority,source:r.source,platform:r.platform,appVersion:r.app_version,buildNumber:r.build_number,runtimeVersion:r.runtime_version,osVersion:r.os_version,deviceModel:r.device_model,route:r.route,networkType:r.network_type,correlationId:r.correlation_id,hasAttachment:Boolean(r.attachment_bytes),assignedTo:r.assigned_to?{id:r.assigned_to,name:r.assigned_name}:null,resolvedAt:r.resolved_at?.toISOString?.()??r.resolved_at,closedAt:r.closed_at?.toISOString?.()??r.closed_at,createdAt:r.created_at.toISOString(),updatedAt:r.updated_at.toISOString()});

export const createGrievance=async(i:GrievanceInput)=>{const client=await pool.connect();try{await client.query('begin');const id=crypto.randomUUID();const reference=`GRV-${new Date().getUTCFullYear()}-${id.replace(/-/g,'').slice(0,8).toUpperCase()}`;const inserted=await client.query(`insert into grievances(id,reference_id,user_id,client_id,client_request_id,category,subject,description,contact_preference,platform,app_version,build_number,runtime_version,os_version,device_model,route,network_type,correlation_id,attachment_content_type,attachment_byte_length,attachment_bytes)
 values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21)
 on conflict(user_id,client_request_id) do nothing returning id`,[id,reference,i.userId,i.clientId,i.clientRequestId,i.category,i.subject,i.description,i.contactPreference??null,i.platform,i.appVersion??null,i.buildNumber??null,i.runtimeVersion??null,i.osVersion??null,i.deviceModel??null,i.route??null,i.networkType??null,i.correlationId,i.attachment?.contentType??null,i.attachment?.bytes.length??null,i.attachment?.bytes??null]);
 const resolvedId=inserted.rows[0]?.id??(await client.query('select id from grievances where user_id=$1 and client_request_id=$2',[i.userId,i.clientRequestId])).rows[0].id;
 if(inserted.rowCount)await client.query(`insert into grievance_events(id,grievance_id,actor_user_id,action,new_value) values($1,$2,$3,'CREATED',$4::jsonb)`,[crypto.randomUUID(),resolvedId,i.userId,JSON.stringify({status:'OPEN',priority:'NORMAL'})]);await client.query('commit');return getGrievance(resolvedId,i.userId,true);}catch(e){await client.query('rollback');throw e;}finally{client.release();}};
export const getGrievance=async(id:string,userId?:string,ownOnly=false)=>{const r=await pool.query(`${select} where g.id=$1 ${ownOnly?'and g.user_id=$2':''}`,[id,...(ownOnly?[userId]:[])]);return r.rows[0]?map(r.rows[0]):null;};
export const listMine=async(userId:string)=>{const r=await pool.query(`${select} where g.user_id=$1 order by g.created_at desc limit 100`,[userId]);return r.rows.map(map);};
export const listAdmin=async(q:{search?:string;status?:string;category?:string;platform?:string;priority?:string;from?:string;to?:string;limit:number;offset:number})=>{const values:any[]=[];const where:string[]=[];const add=(sql:string,v:any)=>{values.push(v);where.push(sql.replace('?',`$${values.length}`));};if(q.search){const term=`%${q.search}%`;values.push(term,term,term);where.push(`(g.reference_id ilike $${values.length-2} or u.name ilike $${values.length-1} or g.subject ilike $${values.length})`);}if(q.status)add('g.status=?',q.status);if(q.category)add('g.category=?',q.category);if(q.platform)add('g.platform=?',q.platform);if(q.priority)add('g.priority=?',q.priority);if(q.from)add('g.created_at>=?::timestamptz',q.from);if(q.to)add('g.created_at<=?::timestamptz',q.to);const clause=where.length?`where ${where.join(' and ')}`:'';const count=await pool.query(`select count(*)::int total from grievances g join users u on u.id=g.user_id ${clause}`,values);values.push(q.limit,q.offset);const r=await pool.query(`${select} ${clause} order by g.created_at desc limit $${values.length-1} offset $${values.length}`,values);return{items:r.rows.map(map),total:Number(count.rows[0].total),limit:q.limit,offset:q.offset};};
export const getEvents=async(id:string)=>{const r=await pool.query(`select id,actor_user_id,action,old_value,new_value,note,created_at from grievance_events where grievance_id=$1 order by created_at`,[id]);return r.rows.map(x=>({...x,created_at:x.created_at.toISOString()}));};
export const mutateGrievance=async(id:string,actorId:string,patch:{status?:GrievanceStatus;priority?:GrievancePriority;assignedTo?:string|null;note?:string})=>{const client=await pool.connect();try{await client.query('begin');const old=(await client.query('select status,priority,assigned_to from grievances where id=$1 for update',[id])).rows[0];if(!old){await client.query('rollback');return null;}const next={status:patch.status??old.status,priority:patch.priority??old.priority,assignedTo:patch.assignedTo===undefined?old.assigned_to:patch.assignedTo};await client.query(`update grievances set status=$2,priority=$3,assigned_to=$4,resolved_at=case when $2='RESOLVED' then coalesce(resolved_at,now()) else resolved_at end,closed_at=case when $2='CLOSED' then coalesce(closed_at,now()) else closed_at end,updated_at=now() where id=$1`,[id,next.status,next.priority,next.assignedTo]);const actions:Array<[string,unknown,unknown]>=[];if(next.status!==old.status)actions.push(['STATUS_CHANGED',old.status,next.status]);if(next.priority!==old.priority)actions.push(['PRIORITY_CHANGED',old.priority,next.priority]);if(next.assignedTo!==old.assigned_to)actions.push(['ASSIGNED',old.assigned_to,next.assignedTo]);if(patch.note)actions.push(['NOTE_ADDED',null,null]);for(const [action,oldValue,newValue] of actions)await client.query(`insert into grievance_events(id,grievance_id,actor_user_id,action,old_value,new_value,note) values($1,$2,$3,$4,$5::jsonb,$6::jsonb,$7)`,[crypto.randomUUID(),id,actorId,action,oldValue==null?null:JSON.stringify(oldValue),newValue==null?null:JSON.stringify(newValue),action==='NOTE_ADDED'?patch.note:null]);await client.query('commit');return getGrievance(id);}catch(e){await client.query('rollback');throw e;}finally{client.release();}};

export const saveProfilePhoto=async(userId:string,contentType:string,bytes:Buffer)=>{const c=await pool.connect();try{await c.query('begin');await c.query('update profile_photo_assets set replaced_at=now() where user_id=$1 and replaced_at is null',[userId]);const id=crypto.randomUUID();await c.query('insert into profile_photo_assets(id,user_id,content_type,byte_length,bytes) values($1,$2,$3,$4,$5)',[id,userId,contentType,bytes.length,bytes]);await c.query('update users set profile_photo_asset_id=$2,updated_at=now() where id=$1',[userId,id]);await c.query('commit');return{id,contentType,byteLength:bytes.length};}catch(e){await c.query('rollback');throw e;}finally{c.release();}};
export const readProfilePhoto=async(userId:string)=>{const r=await pool.query(`select a.content_type,a.bytes,a.created_at from users u join profile_photo_assets a on a.id=u.profile_photo_asset_id where u.id=$1 and a.user_id=$1`,[userId]);return r.rows[0]??null;};
