import { readFileSync } from 'node:fs';
import { closePool, getPool } from '../src/db/pool.js';
import { migrateDatabase } from '../src/db/migrator.js';
type Decision={decisionId:string;referenceItemId:string;referenceCanonicalName:string;finalStatus:string;governedFoodId:string|null;runtimeFoodId:string|null;aliasTarget:string|null;duplicateTarget:string|null;parentTarget:string|null;sourceMappingId:string|null;evidenceStatus:string;operationalUse:string;processorVersion:string};
const artifact=JSON.parse(readFileSync(new URL('../src/modules/nutrition/food-curation/data/food_reference_reconciliation_v17_36.json',import.meta.url),'utf8')) as {schemaVersion:string;startingCohortCount:number;finalUnprocessedCount:number;artifactSha256:string;decisions:Decision[]};
const validate=()=>{if(artifact.schemaVersion!=='FITEATSY_FOOD_REFERENCE_RECONCILIATION_V17_36'||artifact.startingCohortCount!==128||artifact.decisions.length!==128||artifact.finalUnprocessedCount!==0||new Set(artifact.decisions.map(x=>x.referenceItemId)).size!==128)throw new Error('V17_36_ARTIFACT_INVALID');};
const main=async()=>{validate();await migrateDatabase();const client=await getPool().connect();let persisted=0,unchanged=0;try{await client.query('begin');await client.query('select pg_advisory_xact_lock($1,$2)',[20260907,36]);for(const d of artifact.decisions){const r=await client.query(`insert into food_reference_reconciliation_v17_36(decision_id,reference_item_id,canonical_name,final_status,governed_food_id,runtime_food_id,alias_target,duplicate_target,parent_target,source_mapping_id,evidence_status,operational_use,processor_version,artifact_hash,decision_payload) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15::jsonb) on conflict(reference_item_id) do update set canonical_name=excluded.canonical_name,final_status=excluded.final_status,governed_food_id=excluded.governed_food_id,runtime_food_id=excluded.runtime_food_id,alias_target=excluded.alias_target,duplicate_target=excluded.duplicate_target,parent_target=excluded.parent_target,source_mapping_id=excluded.source_mapping_id,evidence_status=excluded.evidence_status,operational_use=excluded.operational_use,processor_version=excluded.processor_version,artifact_hash=excluded.artifact_hash,decision_payload=excluded.decision_payload,updated_at=now() where food_reference_reconciliation_v17_36.decision_payload<>excluded.decision_payload or food_reference_reconciliation_v17_36.artifact_hash<>excluded.artifact_hash`,[d.decisionId,d.referenceItemId,d.referenceCanonicalName,d.finalStatus,d.governedFoodId,d.runtimeFoodId,d.aliasTarget,d.duplicateTarget,d.parentTarget,d.sourceMappingId,d.evidenceStatus,d.operationalUse,d.processorVersion,artifact.artifactSha256,JSON.stringify(d)]);r.rowCount?persisted++:unchanged++;}
await client.query(`update food_catalogue_reference_items r set processing_status=case when i.reference_item_id is not null then 'TRIAGED_PENDING_EVIDENCE' else 'VERIFIED' end,processing_version=case when i.reference_item_id is not null then i.processor_version when p.reference_item_id is not null then 'P0_VERIFICATION_V17_30A' else r.processing_version end,evidence_status=case when i.reference_item_id is not null then 'INDIA_LAB_VALIDATION_REQUIRED' else coalesce(p.evidence_status,r.evidence_status) end,operational_use_state=coalesce(p.operational_use_state,r.operational_use_state) from food_reference_reconciliation_v17_36 stale left join food_india_resolution_v17_35 i on i.reference_item_id=stale.reference_item_id left join food_catalogue_p0_verification_decisions p on p.reference_item_id=stale.reference_item_id where r.id=stale.reference_item_id and stale.artifact_hash<>$1`,[artifact.artifactSha256]);
await client.query('delete from food_reference_reconciliation_v17_36 where artifact_hash<>$1',[artifact.artifactSha256]);
await client.query(`update food_catalogue_reference_items r set processing_status=case when d.final_status='INDIA_LAB_VALIDATION_REQUIRED' then 'TRIAGED_PENDING_EVIDENCE' else 'VERIFIED' end,processing_version='FOOD_REFERENCE_RECONCILIATION_V17_36',evidence_status=d.evidence_status,operational_use_state=d.operational_use from food_reference_reconciliation_v17_36 d where r.id=d.reference_item_id and d.artifact_hash=$1`,[artifact.artifactSha256]);
const count=await client.query(`select count(*)::int total,count(*) filter(where r.processing_status='UNPROCESSED' and r.evidence_status='AUTHORITATIVE_SOURCE_AND_SERVING_REQUIRED')::int unprocessed from food_reference_reconciliation_v17_36 d join food_catalogue_reference_items r on r.id=d.reference_item_id where d.artifact_hash=$1`,[artifact.artifactSha256]);if(Number(count.rows[0].total)!==128||Number(count.rows[0].unprocessed)!==0)throw new Error('V17_36_PERSISTENCE_ACCOUNTING_MISMATCH');await client.query('commit');console.log(JSON.stringify({decisions:128,persisted,unchanged,finalUnprocessed:Number(count.rows[0].unprocessed),artifactSha256:artifact.artifactSha256}));}catch(e){await client.query('rollback');throw e;}finally{client.release();await closePool();}};
void main().catch(async e=>{console.error(e instanceof Error?e.message:e);await closePool();process.exitCode=1;});
