import crypto from 'node:crypto';
import type { AuthenticatedAccount } from '../auth/auth.repository.js';
import { pool } from '../../db/pool.js';
import { resolveActiveTenantContext } from '../tenancy/tenant-context.js';
import { ExternalClientError } from './external-clients.repository.js';

export const EXTERNAL_DOCUMENT_CATEGORIES=['LAB_REPORT','PRESCRIPTION','MEDICAL_REPORT','IMAGING_REPORT','DISCHARGE_SUMMARY','OTHER_HEALTH_DOCUMENT'] as const;
export const EXTERNAL_DOCUMENT_MAX_BYTES=Number(process.env.EXTERNAL_DOCUMENT_MAX_BYTES||12*1024*1024);
const safeName=(name:string)=>name.replace(/[\\/\0\r\n]/g,'_').replace(/[^\p{L}\p{N}._ -]/gu,'_').slice(0,180)||'document';
const detectedMime=(buffer:Buffer)=>buffer.subarray(0,5).toString()==='%PDF-'?'application/pdf':buffer[0]===0xff&&buffer[1]===0xd8&&buffer[2]===0xff?'image/jpeg':buffer.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))?'image/png':null;
export const validateExternalDocumentFile=(input:{fileName:string;mimeType:string;buffer:Buffer})=>{if(!input.buffer.length||input.buffer.length>EXTERNAL_DOCUMENT_MAX_BYTES)throw new ExternalClientError('DOCUMENT_SIZE_INVALID',413,'Document exceeds the configured size limit.');const mime=detectedMime(input.buffer);if(!mime||mime!==input.mimeType)throw new ExternalClientError('DOCUMENT_TYPE_INVALID',400,'Document content does not match a supported PDF, JPEG, or PNG type.');return{mimeType:mime,fileName:safeName(input.fileName)};};
const scope=async(account:AuthenticatedAccount,clientId:string)=>{const tenant=await resolveActiveTenantContext(account);if(!tenant||tenant.tenantType==='ZESTIVA_INTERNAL'||!['OWNER','CONSULTANT'].includes(tenant.currentMembershipRole))throw new ExternalClientError('EXTERNAL_DOCUMENT_AUTHORITY_REQUIRED',403,'External practice authority is required.');const client=await pool.query('select id from external_clients where id=$1 and tenant_id=$2 and deleted_at is null',[clientId,tenant.tenantId]);if(!client.rowCount)throw new ExternalClientError('EXTERNAL_CLIENT_NOT_FOUND',404,'Client not found.');return tenant.tenantId;};
const publicDocument=(row:any)=>({id:row.id,category:row.category,originalFilename:row.original_filename,displayName:row.display_name,mimeType:row.mime_type,fileSizeBytes:row.file_size_bytes,source:row.source,uploadedByUserId:row.uploaded_by_user_id,documentDate:row.document_date,providerName:row.provider_name,notes:row.notes,status:row.status,processingStatus:row.processing_status,createdAt:row.created_at,updatedAt:row.updated_at,uploadedAt:row.uploaded_at});
const audit=(db:any,tenantId:string,clientId:string,actor:string,event:string,documentId:string,fields?:string[])=>db.query('insert into external_client_audit_events(id,tenant_id,client_id,actor_user_id,event_type,metadata) values($1,$2,$3,$4,$5,$6::jsonb)',[crypto.randomUUID(),tenantId,clientId,actor,event,JSON.stringify({documentId,...(fields?{fields}:{})})]);
export type DocumentReadyForProcessing={document_id:string;tenant_id:string;client_id:string;category:string;storage_reference:string;mime_type:string;document_date:string|null};
export const uploadExternalClientDocument=async(account:AuthenticatedAccount,clientId:string,input:any)=>{const tenantId=await scope(account,clientId);const valid=validateExternalDocumentFile(input);const hash=crypto.createHash('sha256').update(input.buffer).digest('hex');const existing=await pool.query("select id from external_client_documents where tenant_id=$1 and client_id=$2 and content_hash=$3 and status='ACTIVE'",[tenantId,clientId,hash]);if(existing.rowCount)throw new ExternalClientError('DOCUMENT_DUPLICATE',409,'This file already exists for the client.');const id=crypto.randomUUID();const result=await pool.query(`insert into external_client_documents(id,tenant_id,client_id,category,original_filename,display_name,mime_type,file_size_bytes,storage_reference,source,uploaded_by_user_id,document_date,provider_name,notes,content_hash,original_file)
values($1,$2,$3,$4,$5,$6,$7,$8,$9,'CONSULTANT_UPLOAD',$10,$11,$12,$13,$14,$15) returning *`,[id,tenantId,clientId,input.category,valid.fileName,safeName(input.displayName||valid.fileName),valid.mimeType,input.buffer.length,id,account.user.id,input.documentDate||null,input.providerName||null,input.notes||null,hash,input.buffer]);await audit(pool,tenantId,clientId,account.user.id,'CLIENT_DOCUMENT_UPLOADED',id);return publicDocument(result.rows[0]);};
export const listExternalClientDocuments=async(account:AuthenticatedAccount,clientId:string)=>{const tenantId=await scope(account,clientId);const result=await pool.query("select * from external_client_documents where tenant_id=$1 and client_id=$2 and status='ACTIVE' order by uploaded_at desc",[tenantId,clientId]);return result.rows.map(publicDocument);};
export const getExternalClientDocumentMetadata=async(account:AuthenticatedAccount,clientId:string,documentId:string)=>{const tenantId=await scope(account,clientId);const result=await pool.query("select * from external_client_documents where id=$1 and client_id=$2 and tenant_id=$3 and status='ACTIVE'",[documentId,clientId,tenantId]);if(!result.rowCount)throw new ExternalClientError('DOCUMENT_NOT_FOUND',404,'Document not found.');return publicDocument(result.rows[0]);};
export const downloadExternalClientDocument=async(account:AuthenticatedAccount,clientId:string,documentId:string)=>{const tenantId=await scope(account,clientId);const result=await pool.query("select * from external_client_documents where id=$1 and client_id=$2 and tenant_id=$3 and status='ACTIVE'",[documentId,clientId,tenantId]);if(!result.rowCount)throw new ExternalClientError('DOCUMENT_NOT_FOUND',404,'Document not found.');await audit(pool,tenantId,clientId,account.user.id,'CLIENT_DOCUMENT_DOWNLOADED',documentId);return result.rows[0];};
export const updateExternalClientDocument=async(account:AuthenticatedAccount,clientId:string,documentId:string,input:any)=>{const tenantId=await scope(account,clientId);const fields=Object.keys(input);const result=await pool.query(`update external_client_documents set display_name=coalesce($1,display_name),category=coalesce($2,category),document_date=coalesce($3,document_date),provider_name=coalesce($4,provider_name),notes=coalesce($5,notes),updated_at=now() where id=$6 and client_id=$7 and tenant_id=$8 and status='ACTIVE' returning *`,[input.displayName,input.category,input.documentDate,input.providerName,input.notes,documentId,clientId,tenantId]);if(!result.rowCount)throw new ExternalClientError('DOCUMENT_NOT_FOUND',404,'Document not found.');await audit(pool,tenantId,clientId,account.user.id,'CLIENT_DOCUMENT_METADATA_UPDATED',documentId,fields);return publicDocument(result.rows[0]);};
export const archiveExternalClientDocument=async(account:AuthenticatedAccount,clientId:string,documentId:string)=>{const tenantId=await scope(account,clientId);const result=await pool.query("update external_client_documents set status='ARCHIVED',updated_at=now() where id=$1 and client_id=$2 and tenant_id=$3 and status='ACTIVE' returning id",[documentId,clientId,tenantId]);if(!result.rowCount)throw new ExternalClientError('DOCUMENT_NOT_FOUND',404,'Document not found.');await audit(pool,tenantId,clientId,account.user.id,'CLIENT_DOCUMENT_ARCHIVED',documentId);return{status:'ARCHIVED'};};
