import crypto from 'node:crypto';
import type { PoolClient } from 'pg';
import { pool } from '../../db/pool.js';
import type { AuthenticatedAccount } from '../auth/auth.repository.js';
import { resolveActiveTenantContext, type TenantContext } from '../tenancy/tenant-context.js';

type Queryable=Pick<PoolClient,'query'>;
export type ExternalClientStatus='INVITED'|'INTAKE_STARTED'|'INTAKE_COMPLETED'|'ACTIVE'|'INACTIVE';
export type ExternalClientGender='FEMALE'|'MALE'|'NON_BINARY'|'PREFER_NOT_TO_SAY'|'OTHER';
export class ExternalClientError extends Error{constructor(public code:string,public status:number,message:string){super(message);}}
const mapRow=(r:any)=>({id:r.id,tenantId:r.tenant_id,firstName:r.first_name,lastName:r.last_name,displayName:r.display_name,mobile:r.mobile,email:r.email,dateOfBirth:r.date_of_birth,gender:r.gender,status:r.status,intakeState:r.intake_state,intakeCompletionPercent:r.intake_completion_percent??0,intakeLastSavedAt:r.intake_last_saved_at??null,intakeSubmittedAt:r.intake_submitted_at??null,source:r.source,createdByUserId:r.created_by_user_id,profilePhotoUrl:r.profile_photo_url,notesSummary:r.notes_summary,invitationStatus:r.invitation_status??null,createdAt:r.created_at,updatedAt:r.updated_at});
const tenantFor=async(account:AuthenticatedAccount):Promise<TenantContext>=>{const tenant=await resolveActiveTenantContext(account);if(!tenant)throw new ExternalClientError('TENANT_CONTEXT_REQUIRED',403,'An active tenant membership is required.');if(tenant.tenantType==='ZESTIVA_INTERNAL')throw new ExternalClientError('EXTERNAL_WORKSPACE_REQUIRED',403,'External clients are unavailable in the in-house workspace.');if(!['OWNER','CONSULTANT'].includes(tenant.currentMembershipRole))throw new ExternalClientError('EXTERNAL_CLIENT_ROLE_REQUIRED',403,'Owner or Consultant access is required.');return tenant;};
export const normaliseExternalClientMobile=(value:string|null|undefined)=>{if(!value)return null;const digits=value.replace(/\D/g,'');if(digits.length===10)return `91${digits}`;if(digits.length<8||digits.length>15)throw new ExternalClientError('INVALID_MOBILE',400,'Enter a valid mobile number.');return digits;};
export const normaliseExternalClientEmail=(value:string|null|undefined)=>value?.trim().toLowerCase()||null;
const audit=async(db:Queryable,input:{tenantId:string;clientId:string;actorId:string;event:string;metadata?:object})=>db.query(`insert into external_client_audit_events(id,tenant_id,client_id,actor_user_id,event_type,metadata) values($1,$2,$3,$4,$5,$6::jsonb)`,[crypto.randomUUID(),input.tenantId,input.clientId,input.actorId,input.event,JSON.stringify(input.metadata??{})]);
export const createExternalClient=async(account:AuthenticatedAccount,input:{firstName:string;lastName:string;mobile?:string|null;email?:string|null;dateOfBirth?:string|null;gender?:ExternalClientGender|null;notesSummary?:string|null})=>{const tenant=await tenantFor(account);const mobile=normaliseExternalClientMobile(input.mobile);const email=normaliseExternalClientEmail(input.email);if(!mobile&&!email)throw new ExternalClientError('CLIENT_CONTACT_REQUIRED',400,'A mobile number or email address is required.');const db=await pool.connect();try{await db.query('begin');const id=crypto.randomUUID();const displayName=`${input.firstName.trim()} ${input.lastName.trim()}`.trim();const result=await db.query(`insert into external_clients(id,tenant_id,first_name,last_name,display_name,mobile,mobile_normalized,email,email_normalized,date_of_birth,gender,status,intake_state,source,created_by_user_id,notes_summary) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'ACTIVE','NOT_STARTED','CONSULTANT_ENTERED',$12,$13) returning *`,[id,tenant.tenantId,input.firstName.trim(),input.lastName.trim(),displayName,input.mobile?.trim()||null,mobile,input.email?.trim()||null,email,input.dateOfBirth||null,input.gender||null,account.user.id,input.notesSummary?.trim()||null]);await audit(db,{tenantId:tenant.tenantId,clientId:id,actorId:account.user.id,event:'CLIENT_CREATED',metadata:{source:'CONSULTANT_ENTERED',status:'ACTIVE'}});await db.query('commit');return mapRow(result.rows[0]);}catch(error:any){await db.query('rollback');if(error?.code==='23505')throw new ExternalClientError('EXTERNAL_CLIENT_DUPLICATE_CONTACT',409,'A client with this contact already exists in this practice.');throw error;}finally{db.release();}};
const clientProjection=`external_clients.*,(select i.status from external_client_invitations i where i.client_id=external_clients.id and i.tenant_id=external_clients.tenant_id order by i.created_at desc limit 1) invitation_status,(select x.completion_percent from external_client_intakes x where x.client_id=external_clients.id and x.tenant_id=external_clients.tenant_id order by x.updated_at desc limit 1) intake_completion_percent,(select x.last_saved_at from external_client_intakes x where x.client_id=external_clients.id and x.tenant_id=external_clients.tenant_id order by x.updated_at desc limit 1) intake_last_saved_at,(select x.submitted_at from external_client_intakes x where x.client_id=external_clients.id and x.tenant_id=external_clients.tenant_id order by x.updated_at desc limit 1) intake_submitted_at`;
export const listExternalClients=async(account:AuthenticatedAccount,input:{q?:string;status?:ExternalClientStatus;limit:number;offset:number})=>{const tenant=await tenantFor(account);const q=input.q?.trim()||null;const values:any[]=[tenant.tenantId,input.status??null,q?`%${q}%`:null,input.limit,input.offset];const where=`tenant_id=$1 and deleted_at is null and ($2::text is null or status=$2) and ($3::text is null or display_name ilike $3 or email ilike $3 or mobile ilike $3)`;const [rows,count]=await Promise.all([pool.query(`select ${clientProjection} from external_clients where ${where} order by updated_at desc limit $4 offset $5`,values),pool.query(`select count(*)::int as count from external_clients where ${where}`,values.slice(0,3))]);return{clients:rows.rows.map(mapRow),pagination:{total:Number(count.rows[0]?.count??0),limit:input.limit,offset:input.offset}};};
export const getExternalClient=async(account:AuthenticatedAccount,id:string)=>{const tenant=await tenantFor(account);const result=await pool.query(`select ${clientProjection} from external_clients where id=$1 and tenant_id=$2 and deleted_at is null`,[id,tenant.tenantId]);return result.rows[0]?mapRow(result.rows[0]):null;};
export const updateExternalClient=async(account:AuthenticatedAccount,id:string,input:Record<string,any>)=>{const tenant=await tenantFor(account);const current=await getExternalClient(account,id);if(!current)return null;const next={firstName:input.firstName??current.firstName,lastName:input.lastName??current.lastName,mobile:input.mobile===undefined?current.mobile:input.mobile,email:input.email===undefined?current.email:input.email,dateOfBirth:input.dateOfBirth===undefined?current.dateOfBirth:input.dateOfBirth,gender:input.gender===undefined?current.gender:input.gender,status:input.status??current.status,notesSummary:input.notesSummary===undefined?current.notesSummary:input.notesSummary};const mobile=normaliseExternalClientMobile(next.mobile);const email=normaliseExternalClientEmail(next.email);if(!mobile&&!email)throw new ExternalClientError('CLIENT_CONTACT_REQUIRED',400,'A mobile number or email address is required.');const db=await pool.connect();try{await db.query('begin');const result=await db.query(`update external_clients set first_name=$3,last_name=$4,display_name=$5,mobile=$6,mobile_normalized=$7,email=$8,email_normalized=$9,date_of_birth=$10,gender=$11,status=$12,notes_summary=$13,updated_at=now() where id=$1 and tenant_id=$2 and deleted_at is null returning *`,[id,tenant.tenantId,next.firstName.trim(),next.lastName.trim(),`${next.firstName.trim()} ${next.lastName.trim()}`.trim(),next.mobile?.trim()||null,mobile,next.email?.trim()||null,email,next.dateOfBirth||null,next.gender||null,next.status,next.notesSummary?.trim()||null]);await audit(db,{tenantId:tenant.tenantId,clientId:id,actorId:account.user.id,event:'CLIENT_UPDATED'});if(next.status!==current.status)await audit(db,{tenantId:tenant.tenantId,clientId:id,actorId:account.user.id,event:'CLIENT_STATUS_CHANGED',metadata:{from:current.status,to:next.status}});await db.query('commit');return mapRow(result.rows[0]);}catch(error:any){await db.query('rollback');if(error?.code==='23505')throw new ExternalClientError('EXTERNAL_CLIENT_DUPLICATE_CONTACT',409,'A client with this contact already exists in this practice.');throw error;}finally{db.release();}};
