import crypto from 'node:crypto';
import { pool } from '../../db/pool.js';
import { env } from '../../config/env.js';
import type { AuthenticatedAccount } from '../auth/auth.repository.js';
import { resolveActiveTenantContext } from '../tenancy/tenant-context.js';
import { ExternalClientError } from './external-clients.repository.js';

const hashToken=(token:string)=>crypto.createHash('sha256').update(token).digest('hex');
const mapInvitation=(r:any)=>({id:r.id,clientId:r.client_id,status:r.status,createdAt:r.created_at,expiresAt:r.expires_at,revokedAt:r.revoked_at,firstOpenedAt:r.first_opened_at,lastOpenedAt:r.last_opened_at,completedAt:r.completed_at});
const authority=async(account:AuthenticatedAccount)=>{const tenant=await resolveActiveTenantContext(account);if(!tenant||tenant.tenantType==='ZESTIVA_INTERNAL'||!['OWNER','CONSULTANT'].includes(tenant.currentMembershipRole))throw new ExternalClientError('EXTERNAL_CLIENT_INVITATION_AUTHORITY_REQUIRED',403,'External Consultant authority is required.');return tenant;};
const audit=(db:any,input:{tenantId:string;clientId:string;invitationId:string;event:string;actorId?:string|null})=>db.query(`insert into external_client_audit_events(id,tenant_id,client_id,actor_user_id,event_type,metadata) values($1,$2,$3,$4,$5,$6::jsonb)`,[crypto.randomUUID(),input.tenantId,input.clientId,input.actorId??null,input.event,JSON.stringify({invitationId:input.invitationId})]);
const issue=async(account:AuthenticatedAccount,clientId:string,regenerate:boolean)=>{const tenant=await authority(account);const db=await pool.connect();try{await db.query('begin');const owned=await db.query(`select id from external_clients where id=$1 and tenant_id=$2 and deleted_at is null for update`,[clientId,tenant.tenantId]);if(!owned.rowCount)throw new ExternalClientError('EXTERNAL_CLIENT_NOT_FOUND',404,'Client not found.');const prior=await db.query(`update external_client_invitations set status='REVOKED',revoked_at=now(),revoked_by_user_id=$3 where client_id=$1 and tenant_id=$2 and status in ('PENDING','OPENED') returning id`,[clientId,tenant.tenantId,account.user.id]);for(const row of prior.rows)await audit(db,{tenantId:tenant.tenantId,clientId,invitationId:row.id,event:'CLIENT_INVITATION_REVOKED',actorId:account.user.id});const rawToken=crypto.randomBytes(32).toString('base64url');const id=crypto.randomUUID();const expiresAt=new Date(Date.now()+env.externalClientInvitationTtlDays*86400000);const result=await db.query(`insert into external_client_invitations(id,tenant_id,client_id,token_hash,status,created_by_user_id,expires_at) values($1,$2,$3,$4,'PENDING',$5,$6) returning *`,[id,tenant.tenantId,clientId,hashToken(rawToken),account.user.id,expiresAt.toISOString()]);await audit(db,{tenantId:tenant.tenantId,clientId,invitationId:id,event:regenerate||prior.rowCount?'CLIENT_INVITATION_REGENERATED':'CLIENT_INVITATION_CREATED',actorId:account.user.id});await db.query('commit');return{invitation:mapInvitation(result.rows[0]),shareUrl:`${env.externalClientIntakeBaseUrl}/${rawToken}`};}catch(error){await db.query('rollback');throw error;}finally{db.release();}};
export const createExternalClientInvitation=(account:AuthenticatedAccount,clientId:string)=>issue(account,clientId,false);
export const regenerateExternalClientInvitation=(account:AuthenticatedAccount,clientId:string)=>issue(account,clientId,true);
export const getCurrentExternalClientInvitation=async(account:AuthenticatedAccount,clientId:string)=>{const tenant=await authority(account);const owned=await pool.query(`select id from external_clients where id=$1 and tenant_id=$2 and deleted_at is null`,[clientId,tenant.tenantId]);if(!owned.rowCount)throw new ExternalClientError('EXTERNAL_CLIENT_NOT_FOUND',404,'Client not found.');await pool.query(`update external_client_invitations set status='EXPIRED' where client_id=$1 and tenant_id=$2 and status in ('PENDING','OPENED') and expires_at<=now()`,[clientId,tenant.tenantId]);const result=await pool.query(`select * from external_client_invitations where client_id=$1 and tenant_id=$2 order by created_at desc limit 1`,[clientId,tenant.tenantId]);return result.rows[0]?mapInvitation(result.rows[0]):null;};
export const revokeExternalClientInvitation=async(account:AuthenticatedAccount,clientId:string)=>{const tenant=await authority(account);const db=await pool.connect();try{await db.query('begin');const result=await db.query(`update external_client_invitations i set status='REVOKED',revoked_at=now(),revoked_by_user_id=$3 from external_clients c where i.client_id=$1 and i.tenant_id=$2 and c.id=i.client_id and c.tenant_id=i.tenant_id and c.deleted_at is null and i.status in ('PENDING','OPENED') returning i.*`,[clientId,tenant.tenantId,account.user.id]);if(!result.rowCount)throw new ExternalClientError('ACTIVE_INVITATION_NOT_FOUND',404,'No active invitation was found.');await audit(db,{tenantId:tenant.tenantId,clientId,invitationId:result.rows[0].id,event:'CLIENT_INVITATION_REVOKED',actorId:account.user.id});await db.query('commit');return mapInvitation(result.rows[0]);}catch(error){await db.query('rollback');throw error;}finally{db.release();}};
export const openExternalClientInvitation=async(rawToken:string)=>{if(!/^[A-Za-z0-9_-]{40,100}$/.test(rawToken))throw new ExternalClientError('INVITATION_INVALID',404,'This invitation is invalid or unavailable.');const db=await pool.connect();try{await db.query('begin');const result=await db.query(`select i.*,c.display_name,t.name practice_name,u.name practitioner_name from external_client_invitations i join external_clients c on c.id=i.client_id and c.tenant_id=i.tenant_id join tenants t on t.id=i.tenant_id join users u on u.id=i.created_by_user_id where i.token_hash=$1 and c.deleted_at is null for update of i`,[hashToken(rawToken)]);if(!result.rowCount)throw new ExternalClientError('INVITATION_INVALID',404,'This invitation is invalid or unavailable.');const row=result.rows[0];if(row.status==='REVOKED')throw new ExternalClientError('INVITATION_REVOKED',410,'This invitation is no longer available.');if(row.status==='COMPLETED'){await db.query('commit');return{state:'COMPLETED',practiceName:row.practice_name||row.practitioner_name,clientName:row.display_name};}if(row.status==='EXPIRED'||new Date(row.expires_at)<=new Date()){if(row.status!=='EXPIRED')await db.query(`update external_client_invitations set status='EXPIRED' where id=$1`,[row.id]);await db.query('commit');throw new ExternalClientError('INVITATION_EXPIRED',410,'This invitation has expired.');}await db.query(`update external_client_invitations set status='OPENED',first_opened_at=coalesce(first_opened_at,now()),last_opened_at=now() where id=$1`,[row.id]);if(row.status==='PENDING')await audit(db,{tenantId:row.tenant_id,clientId:row.client_id,invitationId:row.id,event:'CLIENT_INVITATION_OPENED'});await db.query('commit');return{state:'VALID',practiceName:row.practice_name||row.practitioner_name,clientName:row.display_name,expiresAt:new Date(row.expires_at).toISOString()};}catch(error){try{await db.query('rollback');}catch{}throw error;}finally{db.release();}};
export const invitationTokenFingerprintForTests=hashToken;
