import assert from 'node:assert/strict';
import test from 'node:test';
import { randomUUID } from 'node:crypto';
import { closePool, getPool } from '../../backend/src/db/pool.js';
import { migrateDatabase, resetMigrationStateForTests } from '../../backend/src/db/migrator.js';
import { activateTemplate, createTemplate, createTemplateRevision, getTemplate, listTemplates } from '../../backend/src/modules/nutrition/consultant-meal-templates.repository.js';
import { templateStructureHash, type TemplateStructure } from '../../backend/src/modules/nutrition/consultant-meal-template.domain.js';

const databaseTest=process.env.DATABASE_URL?test:test.skip;
const owner=`qa-template-owner-${randomUUID()}`;const teammate=`qa-template-member-${randomUUID()}`;const outsider=`qa-template-outsider-${randomUUID()}`;const team=`qa-template-team-${randomUUID()}`;
const structure=(name:string):TemplateStructure=>({name,mealHead:'LUNCH',mealStructure:{kind:'BALANCED'},components:[{semanticRole:'BREAD',catalogEntityId:'CF_CHAPATI',servingSelection:{servingId:'CF_CHAPATI_PIECE',multiplier:2},servingLock:true,order:0}],visibility:'TEAM',teamId:team});
databaseTest.before(async()=>{resetMigrationStateForTests();await migrateDatabase();const pool=getPool();for(const id of [owner,teammate,outsider])await pool.query(`insert into users(id,name,role,status) values($1,$2,'consultant','active') on conflict(id) do nothing`,[id,id]);await pool.query('insert into consultant_teams(id,name,created_by) values($1,$2,$3)',[team,'QA Template Team',owner]);await pool.query(`insert into consultant_team_members(team_id,consultant_id,role) values($1,$2,'OWNER'),($1,$3,'MEMBER')`,[team,owner,teammate]);});
databaseTest.after(async()=>{const pool=getPool();await pool.query('delete from consultant_meal_template_audit where actor_id=any($1::text[])',[[owner,teammate,outsider]]);await pool.query('update consultant_meal_templates set current_revision_id=null where owner_consultant_id=$1',[owner]);await pool.query('delete from consultant_meal_template_revisions where created_by=$1',[owner]);await pool.query('delete from consultant_meal_templates where owner_consultant_id=$1',[owner]);await pool.query('delete from consultant_team_members where team_id=$1',[team]);await pool.query('delete from consultant_teams where id=$1',[team]);await pool.query('delete from users where id=any($1::text[])',[[owner,teammate,outsider]]);await closePool()});
databaseTest('template lifecycle is immutable, team-scoped and revision-safe',async()=>{const v1=structure('Balanced QA lunch');const created=await createTemplate(owner,v1,templateStructureHash(v1),`TPL_${randomUUID()}`);assert.equal(created.revision.status,'DRAFT');const active1=await activateTemplate(owner,created.id);assert.equal(active1.revision.status,'ACTIVE');assert.ok(await getTemplate(teammate,created.id));assert.equal(await getTemplate(outsider,created.id),null);const v2={...v1,name:'Balanced QA lunch v2'};const draft2=await createTemplateRevision(owner,created.id,v2,templateStructureHash(v2));assert.equal(draft2.revision.number,2);assert.equal((await getTemplate(owner,created.id,active1.revision.id))?.revision.status,'ACTIVE');const active2=await activateTemplate(owner,created.id);assert.equal(active2.revision.number,2);assert.equal((await getTemplate(owner,created.id,active1.revision.id))?.revision.status,'ARCHIVED');const list=await listTemplates(teammate,{mealHead:'LUNCH',status:'ACTIVE',visibility:'TEAM',limit:10,offset:0});assert.equal(list.total,1);});
