import crypto from 'node:crypto';
import { pool } from '../../db/pool.js';
import type { AuthenticatedAccount } from '../auth/auth.repository.js';

export class CommonFoodAdminError extends Error{constructor(public code:string,public statusCode:number,message=code){super(message)}}
const assertAdmin=(account:AuthenticatedAccount)=>{if(!['admin','super_admin','platform_owner'].includes(String(account.user.role).toLowerCase()))throw new CommonFoodAdminError('ADMIN_AUTHORITY_REQUIRED',403)};
export async function listAdminCommonFoods(account:AuthenticatedAccount,q:{active?:boolean;category?:string;family?:string;sourcePolicy?:string;generatorEligible?:boolean;mealHead?:string}){assertAdmin(account);const result=await pool.query(`select f.* from common_foods f where ($1::boolean is null or f.active=$1) and ($2::text is null or f.food_category=$2) and ($3::text is null or f.food_family=$3) and ($4::text is null or f.source_policy_class=$4) and ($5::boolean is null or f.generator_eligible=$5) and ($6::text is null or exists(select 1 from common_food_meal_eligibility e where e.food_id=f.id and e.meal_head=$6 and e.eligible)) order by f.display_name`,[q.active??null,q.category??null,q.family??null,q.sourcePolicy??null,q.generatorEligible??null,q.mealHead??null]);return {items:result.rows};}
export async function inspectAdminCommonFood(account:AuthenticatedAccount,id:string){assertAdmin(account);const [food,aliases,servings,roles,meals,audit]=await Promise.all([pool.query('select * from common_foods where id=$1',[id]),pool.query('select * from common_food_aliases where food_id=$1 order by alias',[id]),pool.query('select * from common_food_servings where food_id=$1 order by serving_version,display_name',[id]),pool.query('select * from common_food_component_roles where food_id=$1 order by role',[id]),pool.query('select * from common_food_meal_eligibility where food_id=$1 order by meal_head,version',[id]),pool.query('select * from common_food_admin_audit where food_id=$1 order by created_at desc',[id])]);if(!food.rows[0])throw new CommonFoodAdminError('COMMON_FOOD_NOT_FOUND',404);return {food:food.rows[0],aliases:aliases.rows,servings:servings.rows,roles:roles.rows,mealEligibility:meals.rows,audit:audit.rows};}
async function audited(account:AuthenticatedAccount,id:string,action:string,reason:string,fn:()=>Promise<void>){assertAdmin(account);const before=await inspectAdminCommonFood(account,id);await fn();const after=await inspectAdminCommonFood(account,id);await pool.query(`insert into common_food_admin_audit(id,actor_user_id,food_id,action,before_snapshot,after_snapshot,reason) values($1,$2,$3,$4,$5,$6,$7)`,[crypto.randomUUID(),account.accountId,id,action,JSON.stringify(before),JSON.stringify(after),reason]);return after;}
export const setAdminCommonFoodState=(a:AuthenticatedAccount,id:string,input:{active?:boolean;generatorEligible?:boolean;reason:string})=>audited(a,id,'SET_STATE',input.reason,async()=>{await pool.query('update common_foods set active=coalesce($2,active),generator_eligible=coalesce($3,generator_eligible),version=version+1,updated_at=now() where id=$1',[id,input.active??null,input.generatorEligible??null]);});
export const addAdminCommonFoodAlias=(a:AuthenticatedAccount,id:string,input:{alias:string;reason:string})=>audited(a,id,'ADD_ALIAS',input.reason,async()=>{await pool.query(`insert into common_food_aliases(id,food_id,alias,normalized_alias,version) values($1,$2,$3,lower(trim($3)),1)`,[crypto.randomUUID(),id,input.alias]);});
export const removeAdminCommonFoodAlias=(a:AuthenticatedAccount,id:string,aliasId:string,reason:string)=>audited(a,id,'REMOVE_ALIAS',reason,async()=>{await pool.query('delete from common_food_aliases where id=$1 and food_id=$2',[aliasId,id]);});
export const addAdminCommonFoodServing=(a:AuthenticatedAccount,id:string,input:{displayName:string;grams:number;minMultiplier:number;maxMultiplier:number;allowedMultipliers:number[];reason:string})=>audited(a,id,'ADD_SERVING_VERSION',input.reason,async()=>{await pool.query(`insert into common_food_servings(id,food_id,serving_version,display_name,quantity,unit,grams_equivalent,conversion_basis,conversion_source,preparation_state,is_default,min_multiplier,max_multiplier,allowed_multipliers,active) values($1,$2,coalesce((select max(serving_version)+1 from common_food_servings where food_id=$2),1),$3,1,'serving',$4,'ADMIN_OPERATIONAL_METADATA','GOVERNED_ADMIN','AS_CATALOGUED',false,$5,$6,$7,true)`,[crypto.randomUUID(),id,input.displayName,input.grams,input.minMultiplier,input.maxMultiplier,JSON.stringify(input.allowedMultipliers)]);});
export const setAdminCommonFoodMeal=(a:AuthenticatedAccount,id:string,input:{mealHead:string;eligible:boolean;reason:string})=>audited(a,id,'SET_MEAL_ELIGIBILITY',input.reason,async()=>{await pool.query(`insert into common_food_meal_eligibility(food_id,meal_head,eligible,priority,constraints,version) values($1,$2,$3,0,'{}',coalesce((select max(version)+1 from common_food_meal_eligibility where food_id=$1 and meal_head=$2),1))`,[id,input.mealHead,input.eligible]);});
export const setAdminCommonFoodRole=(a:AuthenticatedAccount,id:string,input:{role:string;enabled:boolean;reason:string})=>audited(a,id,'SET_COMPONENT_ROLE',input.reason,async()=>{if(input.enabled)await pool.query(`insert into common_food_component_roles(food_id,role,version) values($1,$2,coalesce((select max(version)+1 from common_food_component_roles where food_id=$1 and role=$2),1))`,[id,input.role]);else await pool.query('delete from common_food_component_roles where food_id=$1 and role=$2',[id,input.role]);});
