import React from 'react';
import { Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Screen } from '../../components/Screen'; import { ProfileHeader, ProfileSection } from '../../components/ProfileUi';
import { RootStackParamList } from '../../navigation/types'; import { useAppContext } from '../../state/AppContext'; import { useCanonicalHealthSyncCoordinator } from '../../services/canonicalHealthSyncCoordinator'; import { getThemeColors, spacing, typography } from '../../design/tokens';
type Props=NativeStackScreenProps<RootStackParamList,'ConnectedHealth'>;
export const ConnectedHealthScreen=({navigation}:Props)=>{const {themeMode}=useAppContext();const palette=getThemeColors(themeMode);const health=useCanonicalHealthSyncCoordinator();const provider=Platform.OS==='ios'?'Apple Health':'Health Connect';const connected=health.providerState==='CONNECTED';return <Screen scroll><ProfileHeader navigation={navigation} title="Connected Health"/><Text style={[styles.intro,{color:palette.textMuted}]}>Manage the health platform available on this device and its read permissions.</Text><ProfileSection><View style={styles.hero}><View style={styles.provider}><View style={[styles.icon,{backgroundColor:Platform.OS==='ios'?'#FF375F':'#35B878'}]}><Ionicons name="heart" size={22} color="#fff"/></View><View><Text style={[styles.name,{color:palette.textPrimary}]}>{provider}</Text><Text style={[styles.meta,{color:palette.textMuted}]}>{health.availableMetricCount} metrics available</Text></View></View><Text style={[styles.status,{color:connected?'#2FD36B':'#FF453A'}]}>{connected?'● Connected':'● Not connected'}</Text></View><Pressable style={styles.primary} onPress={()=>navigation.navigate('HealthDataSync',{entryContext:'SETTINGS'})}><Text style={styles.primaryText}>{connected?'Manage Permissions & Sync':`Connect ${provider}`}</Text></Pressable></ProfileSection><View style={[styles.notice,{borderColor:palette.stroke}]}><Ionicons name="information-circle-outline" size={17} color={palette.blue}/><Text style={[styles.meta,{color:palette.textMuted,flex:1}]}>Fiteatsy reads only health metrics you authorise. Availability depends on this device and operating system.</Text></View></Screen>};
const styles=StyleSheet.create({intro:{...typography.body,marginBottom:spacing.lg},hero:{padding:spacing.md,gap:16},provider:{flexDirection:'row',alignItems:'center',gap:12},icon:{width:48,height:48,borderRadius:14,alignItems:'center',justifyContent:'center'},name:{...typography.bodyStrong,fontSize:16},meta:{...typography.caption},status:{...typography.caption},primary:{margin:spacing.md,minHeight:48,borderRadius:12,backgroundColor:'#1689F8',alignItems:'center',justifyContent:'center'},primaryText:{...typography.button,color:'#fff'},notice:{borderWidth:1,borderRadius:14,padding:14,flexDirection:'row',gap:10}});
