import React, { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Image, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import * as ImageManipulator from 'expo-image-manipulator';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Screen } from '../../components/Screen';
import { ProfileHeader, ProfileSection } from '../../components/ProfileUi';
import { getThemeColors, radius, spacing, typography } from '../../design/tokens';
import { RootStackParamList } from '../../navigation/types';
import { AssessmentGender } from '../../types';
import { useAppContext } from '../../state/AppContext';
import { uploadProfilePhoto } from '../../services/profilePhotoService';
import { useProfilePhoto } from '../../hooks/useProfilePhoto';
import { BodyFatSource, ConfirmedProfile, getProfile, saveProfile } from '../../services/profileService';
import { calculateAgeFromDateOfBirth, calculateBmi, calculateBodyFatPercentage, calculateLeanBodyMassKg, calculateWaistHipRatio } from '../../utils/canonicalBodyMetrics';

type Props = NativeStackScreenProps<RootStackParamList, 'MyProfile'>;
const genders: AssessmentGender[] = ['Male', 'Female', 'Prefer not to say'];
export const MyProfileScreen = ({ navigation }: Props) => {
  const { themeMode, onboarding, setOnboarding, authSession } = useAppContext(); const palette = getThemeColors(themeMode);
  const initialName=onboarding?.name ?? authSession?.user.name ?? '';const initialParts=initialName.trim().split(/\s+/);
  const [tab,setTab]=useState<'PERSONAL'|'HEALTH'>('PERSONAL');
  const [firstName,setFirstName]=useState(initialParts.shift()??'');const[lastName,setLastName]=useState(initialParts.join(' '));
  const [dob, setDob] = useState(onboarding?.dateOfBirthISO?.slice(0, 10) ?? '');
  const [location,setLocation]=useState(onboarding?.location??'');
  const [height,setHeight]=useState(onboarding?.heightCm?.toString()??'');const[weight,setWeight]=useState(onboarding?.currentWeightKg?.toString()??'');
  const [waist,setWaist]=useState(onboarding?.waistCm?.toString()??'');const[hip,setHip]=useState(onboarding?.hipCm?.toString()??'');const[neck,setNeck]=useState(onboarding?.neckCm?.toString()??'');
  const [arm,setArm]=useState(onboarding?.armCircumferenceCm?.toString()??'');const[thigh,setThigh]=useState(onboarding?.thighCircumferenceCm?.toString()??'');const[calf,setCalf]=useState(onboarding?.calfCircumferenceCm?.toString()??'');
  const [bodyFat,setBodyFat]=useState(onboarding?.bodyFatPct?.toString()??'');const[bodyFatSource,setBodyFatSource]=useState<BodyFatSource|null>(onboarding?.bodyFatSource??null);const[muscleMass,setMuscleMass]=useState(onboarding?.muscleMassKg?.toString()??'');const[muscleCategory,setMuscleCategory]=useState(onboarding?.muscleMassCategory??'');
  const [gender, setGender] = useState<AssessmentGender | undefined>(onboarding?.gender); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false);
  const photo=useProfilePhoto(authSession?.accountId??'');const[photoBusy,setPhotoBusy]=useState(false);
  const apply=(profile:ConfirmedProfile)=>{setFirstName(profile.firstName);setLastName(profile.lastName);setDob(profile.dateOfBirthISO??'');setGender(profile.gender??undefined);setLocation(profile.location??'');setHeight(profile.heightCm?.toString()??'');setWeight(profile.currentWeightKg?.toString()??'');setWaist(profile.waistCm?.toString()??'');setHip(profile.hipCm?.toString()??'');setNeck(profile.neckCm?.toString()??'');setArm(profile.armCircumferenceCm?.toString()??'');setThigh(profile.thighCircumferenceCm?.toString()??'');setCalf(profile.calfCircumferenceCm?.toString()??'');setBodyFat(profile.bodyFatPct?.toString()??'');setBodyFatSource(profile.bodyFatSource);setMuscleMass(profile.muscleMassKg?.toString()??'');setMuscleCategory(profile.muscleMassCategory??'');};
  useEffect(()=>{let active=true;getProfile().then(value=>{if(active)apply(value);}).catch(()=>undefined);return()=>{active=false;};},[]);
  const choosePhoto=async()=>{if(!authSession?.accountId)return;const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted){Alert.alert('Photos access needed','Allow photo access to choose a profile image.');return;}const picked=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,aspect:[1,1],quality:.85});if(picked.canceled)return;setPhotoBusy(true);try{const resized=await ImageManipulator.manipulateAsync(picked.assets[0].uri,[{resize:{width:720,height:720}}],{compress:.82,format:ImageManipulator.SaveFormat.JPEG,base64:true});if(!resized.base64)throw new Error('Image preparation failed.');const dataUri=`data:image/jpeg;base64,${resized.base64}`;await uploadProfilePhoto({accountId:authSession.accountId,uri:resized.uri,mimeType:'image/jpeg',fileName:'profile-photo.jpg',dataUri});}catch{Alert.alert('Photo not updated','Your current profile photo is unchanged. Check your connection and try again.');}finally{setPhotoBusy(false);}};
  const inputStyle=[styles.input,{color:palette.textPrimary,borderColor:palette.stroke,backgroundColor:palette.cardMuted}];
  const number=(value:string)=>value.trim()===''?null:Number(value);const h=number(height),w=number(weight),wa=number(waist),hi=number(hip),ne=number(neck),bf=number(bodyFat);
  const derived=useMemo(()=>{const estimate=calculateBodyFatPercentage({gender,heightCm:h,waistCm:wa,hipCm:hi,neckCm:ne});const selectedBodyFat=bf??estimate;return{age:calculateAgeFromDateOfBirth(dob),bmi:calculateBmi(h,w),whr:calculateWaistHipRatio(wa,hi),bodyFatEstimate:estimate,lbm:calculateLeanBodyMassKg(w,selectedBodyFat)};},[dob,gender,h,w,wa,hi,ne,bf]);
  const mergeLocal=(confirmed:ConfirmedProfile)=>{if(!onboarding)return;setOnboarding({...onboarding,name:confirmed.name,dateOfBirthISO:confirmed.dateOfBirthISO??undefined,calculatedAge:calculateAgeFromDateOfBirth(confirmed.dateOfBirthISO)??undefined,gender:confirmed.gender??undefined,location:confirmed.location??undefined,heightCm:confirmed.heightCm??undefined,currentWeightKg:confirmed.currentWeightKg??undefined,waistCm:confirmed.waistCm??undefined,hipCm:confirmed.hipCm??undefined,neckCm:confirmed.neckCm??undefined,armCircumferenceCm:confirmed.armCircumferenceCm??undefined,thighCircumferenceCm:confirmed.thighCircumferenceCm??undefined,calfCircumferenceCm:confirmed.calfCircumferenceCm??undefined,bodyFatPct:confirmed.bodyFatPct??undefined,bodyFatSource:confirmed.bodyFatSource??undefined,bodyFatMeasuredAt:confirmed.bodyFatMeasuredAt??undefined,muscleMassKg:confirmed.muscleMassKg??undefined,muscleMassCategory:confirmed.muscleMassCategory??undefined});};
  const save=async()=>{if(!onboarding)return;if(tab==='PERSONAL'&&(!firstName.trim()||!dob||!gender||derived.age==null)){Alert.alert('Check your details','Enter a valid name, date of birth, and gender.');return;}const numbers=[h,w,wa,hi,ne,number(arm),number(thigh),number(calf),bf,number(muscleMass)];if(tab==='HEALTH'&&numbers.some(value=>value!=null&&!Number.isFinite(value))){Alert.alert('Check your measurements','Use numbers only, or leave an optional field empty.');return;}if(tab==='HEALTH'&&bf!=null&&!bodyFatSource){Alert.alert('Body fat source required','Choose how the body-fat value was measured.');return;}setSaving(true);setSaved(false);try{const confirmed=await saveProfile(tab==='PERSONAL'?{section:'PERSONAL',firstName:firstName.trim(),lastName:lastName.trim(),dateOfBirthISO:dob,gender:gender!,location:location.trim()||null}:{section:'HEALTH',heightCm:h,currentWeightKg:w,waistCm:wa,hipCm:hi,neckCm:ne,armCircumferenceCm:number(arm),thighCircumferenceCm:number(thigh),calfCircumferenceCm:number(calf),bodyFatPct:bf,bodyFatSource:bf==null?null:bodyFatSource,bodyFatMeasuredAt:bf==null?null:new Date().toISOString(),muscleMassKg:number(muscleMass),muscleMassCategory:muscleCategory.trim()||null});apply(confirmed);mergeLocal(confirmed);setSaved(true);}catch{Alert.alert('Profile not saved','Your edits remain on this screen. Check your connection and try again.');}finally{setSaving(false);}};
  return <Screen scroll><ProfileHeader navigation={navigation} title="My Profile" />
    <View accessibilityRole="tablist" style={[styles.tabs,{backgroundColor:palette.cardMuted}]}>{(['PERSONAL','HEALTH'] as const).map(item=><Pressable key={item} accessibilityRole="tab" accessibilityState={{selected:tab===item}} onPress={()=>{setTab(item);setSaved(false);}} style={[styles.tab,tab===item&&{backgroundColor:palette.blue}]}><Text style={[styles.tabText,{color:tab===item?'#fff':palette.textMuted}]}>{item==='PERSONAL'?'Personal Profile':'Health Profile'}</Text></Pressable>)}</View>
    {tab==='PERSONAL'?<><Pressable accessibilityRole="button" accessibilityLabel="Change profile photo" onPress={()=>void choosePhoto()} style={styles.avatar}>{photo?<Image source={{uri:photo}} style={styles.avatarImage}/>:<Text style={[styles.initials,{color:palette.textPrimary}]}>{`${firstName[0]??''}${lastName[0]??''}`.toUpperCase()||'ME'}</Text>}{photoBusy?<View style={styles.photoBusy}><ActivityIndicator color="#fff"/></View>:null}</Pressable>
    <Pressable onPress={()=>void choosePhoto()}><Text style={[styles.photoNote, { color: palette.blue }]}>Change Photo</Text></Pressable>
    <ProfileSection label="Identity"><View style={styles.two}><Field label="First name"><TextInput accessibilityLabel="First name" value={firstName} onChangeText={setFirstName} style={inputStyle}/></Field><Field label="Last name"><TextInput accessibilityLabel="Last name" value={lastName} onChangeText={setLastName} style={inputStyle}/></Field></View><Field label="Date of birth (YYYY-MM-DD)"><TextInput accessibilityLabel="Date of birth" value={dob} onChangeText={setDob} style={inputStyle}/></Field><Derived label="Age" value={derived.age==null?'Insufficient data':`${derived.age} years`} detail="Calculated from date of birth"/><Field label="Gender"><View style={styles.chips}>{genders.map(item=><Pressable key={item} onPress={()=>setGender(item)} style={[styles.chip,{borderColor:gender===item?palette.blue:palette.stroke,backgroundColor:palette.cardMuted}]}><Text style={{color:palette.textPrimary}}>{item}</Text></Pressable>)}</View></Field></ProfileSection>
    <ProfileSection label="Verified contact"><ReadOnly label="Mobile number" value={authSession?.user.mobileNumber ?? 'Not available'} /><ReadOnly label="Email address" value={authSession?.user.email ?? 'Not available'} /></ProfileSection>
    <ProfileSection label="Location"><Field label="City / region"><TextInput accessibilityLabel="Location" value={location} onChangeText={setLocation} style={inputStyle}/></Field></ProfileSection></>:<>
    <ProfileSection label="Body measurements"><View style={styles.two}><Measure label="Height" unit="cm" value={height} set={setHeight} style={inputStyle}/><Measure label="Weight" unit="kg" value={weight} set={setWeight} style={inputStyle}/></View></ProfileSection>
    <ProfileSection label="Body composition"><Derived label="BMI" value={derived.bmi?.toString()??'Insufficient data'} detail="Calculated from height & weight"/><Field label="Body fat (%)"><TextInput keyboardType="decimal-pad" value={bodyFat} onChangeText={setBodyFat} style={inputStyle}/></Field>{bf!=null?<Field label="Body fat source"><View style={styles.chips}>{(['MANUAL','APPLE_HEALTH','HEALTH_CONNECT','SMART_SCALE','CONSULTANT','OTHER'] as BodyFatSource[]).map(item=><Pressable key={item} onPress={()=>setBodyFatSource(item)} style={[styles.chip,{borderColor:bodyFatSource===item?palette.blue:palette.stroke,backgroundColor:palette.cardMuted}]}><Text style={{color:palette.textPrimary}}>{item.replace('_',' ')}</Text></Pressable>)}</View></Field>:<Derived label="Calculated body fat estimate" value={derived.bodyFatEstimate==null?'Insufficient data':`${derived.bodyFatEstimate}%`} detail="U.S. Navy circumference estimate · not a measurement"/>}<Derived label="Lean body mass" value={derived.lbm==null?'Insufficient data':`${derived.lbm} kg`} detail={`Calculated from weight & ${bf!=null?'entered':'estimated'} body fat`}/><Field label="Muscle mass (kg, optional)"><TextInput keyboardType="decimal-pad" value={muscleMass} onChangeText={setMuscleMass} style={inputStyle}/></Field><Field label="Muscle mass category (optional)"><TextInput value={muscleCategory} onChangeText={setMuscleCategory} style={inputStyle}/></Field></ProfileSection>
    <ProfileSection label="Body circumferences"><View style={styles.two}><Measure label="Waist" unit="cm" value={waist} set={setWaist} style={inputStyle}/><Measure label="Hip" unit="cm" value={hip} set={setHip} style={inputStyle}/></View><Derived label="Waist–hip ratio" value={derived.whr?.toString()??'Insufficient data'} detail="Calculated from waist & hip"/><View style={styles.two}><Measure label="Neck" unit="cm" value={neck} set={setNeck} style={inputStyle}/><Measure label="Mid-upper arm" unit="cm" value={arm} set={setArm} style={inputStyle}/></View><View style={styles.two}><Measure label="Thigh" unit="cm" value={thigh} set={setThigh} style={inputStyle}/><Measure label="Calf" unit="cm" value={calf} set={setCalf} style={inputStyle}/></View></ProfileSection></>}
    {saved?<Text accessibilityRole="alert" style={styles.success}>{tab==='PERSONAL'?'Personal':'Health'} profile saved to your account.</Text>:null}<Pressable accessibilityRole="button" onPress={()=>void save()} disabled={saving||!onboarding} style={[styles.save,!onboarding&&styles.disabled]}>{saving?<ActivityIndicator color="#fff"/>:<Text style={styles.saveText}>Save {tab==='PERSONAL'?'Personal':'Health'} Profile</Text>}</Pressable>
  </Screen>;
};
const Field=({label,children}:{label:string;children:React.ReactNode})=><View style={styles.field}><Text style={styles.label}>{label.toUpperCase()}</Text>{children}</View>;
const Measure=({label,unit,value,set,style}:{label:string;unit:string;value:string;set:(value:string)=>void;style:object})=><Field label={`${label} (${unit})`}><TextInput accessibilityLabel={label} keyboardType="decimal-pad" value={value} onChangeText={set} style={style}/></Field>;
const Derived=({label,value,detail}:{label:string;value:string;detail:string})=><View style={styles.derived}><View><Text style={styles.label}>{label.toUpperCase()}</Text><Text style={styles.derivedValue}>{value}</Text></View><Text style={styles.derivedDetail}>{detail}</Text></View>;
const ReadOnly=({label,value}:{label:string;value:string})=><View style={styles.readonly}><View><Text style={styles.label}>{label.toUpperCase()}</Text><Text style={styles.readValue}>{value}</Text></View><Text style={styles.verified}>✓ Verified</Text></View>;
const styles=StyleSheet.create({tabs:{flexDirection:'row',borderRadius:radius.sm,padding:4,marginBottom:spacing.lg},tab:{flex:1,minHeight:44,borderRadius:radius.sm,alignItems:'center',justifyContent:'center'},tabText:{...typography.caption,fontFamily:'Exo_600SemiBold'},avatar:{width:92,height:92,borderRadius:46,overflow:'hidden',backgroundColor:'#29292D',borderWidth:2,borderColor:'#444',alignSelf:'center',alignItems:'center',justifyContent:'center'},avatarImage:{width:'100%',height:'100%'},photoBusy:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(0,0,0,.45)',alignItems:'center',justifyContent:'center'},initials:{...typography.title},photoNote:{...typography.caption,textAlign:'center',marginVertical:spacing.sm},field:{flex:1,gap:6,padding:spacing.md},label:{...typography.badge,color:'#8D8D94'},input:{minHeight:50,borderWidth:1,borderRadius:radius.sm,paddingHorizontal:spacing.sm,...typography.body},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{borderWidth:1,borderRadius:999,paddingHorizontal:12,paddingVertical:8},two:{flexDirection:'row'},derived:{padding:spacing.md,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#333',gap:5},derivedValue:{...typography.bodyStrong,color:'#fff',marginTop:4},derivedDetail:{...typography.caption,color:'#8D8D94'},readonly:{padding:spacing.md,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#333'},readValue:{...typography.bodyStrong,color:'#fff',marginTop:4},verified:{...typography.caption,color:'#2FD36B'},save:{minHeight:52,borderRadius:radius.sm,backgroundColor:'#1689F8',alignItems:'center',justifyContent:'center',marginBottom:30},saveText:{...typography.button,color:'#fff'},disabled:{opacity:.45},success:{...typography.caption,color:'#2FD36B',textAlign:'center',marginBottom:10}});
