export type StartupState =
  | 'BOOTING'
  | 'LOCAL_SESSION_RESTORE'
  | 'AUTHENTICATED_LOCAL'
  | 'AUTHENTICATING_REMOTE'
  | 'UNAUTHENTICATED'
  | 'READY'
  | 'OFFLINE_READY'
  | 'RECOVERING'
  | 'FATAL_CONFIGURATION_ERROR';

export type StartupEvent =
  | 'RESTORE_LOCAL_SESSION'
  | 'LOCAL_SESSION_FOUND'
  | 'LOCAL_SESSION_EMPTY'
  | 'REMOTE_VALIDATION_STARTED'
  | 'REMOTE_VALIDATION_SUCCEEDED'
  | 'TRANSIENT_NETWORK_FAILURE'
  | 'NETWORK_RECOVERING'
  | 'SESSION_REVOKED'
  | 'FATAL_CONFIGURATION_FAILURE';

const transitions: Record<StartupEvent, StartupState> = {
  RESTORE_LOCAL_SESSION: 'LOCAL_SESSION_RESTORE',
  LOCAL_SESSION_FOUND: 'AUTHENTICATED_LOCAL',
  LOCAL_SESSION_EMPTY: 'UNAUTHENTICATED',
  REMOTE_VALIDATION_STARTED: 'AUTHENTICATING_REMOTE',
  REMOTE_VALIDATION_SUCCEEDED: 'READY',
  TRANSIENT_NETWORK_FAILURE: 'OFFLINE_READY',
  NETWORK_RECOVERING: 'RECOVERING',
  SESSION_REVOKED: 'UNAUTHENTICATED',
  FATAL_CONFIGURATION_FAILURE: 'FATAL_CONFIGURATION_ERROR'
};

export const transitionStartupState = (_current: StartupState, event: StartupEvent): StartupState =>
  transitions[event];

export const startupStateHasVisibleRoute = (state: StartupState): boolean =>
  state !== 'BOOTING' && state !== 'LOCAL_SESSION_RESTORE';
