import assert from 'node:assert/strict';
import test from 'node:test';
import { generateMealCombinations, type CommonFood, type MealComponent, type MealHead } from '../../backend/src/modules/nutrition/common-food-engine.js';
import { addCombinationToDailyUsage, classifyFoodQuality, emptyDailyFoodUsage, optionSimilarity, scoreDayAwareQuality } from '../../backend/src/modules/nutrition/common-food-ranking.js';

const make=(name:string,roles:CommonFood['roles'],heads:MealHead[]=['BREAKFAST','LUNCH','EVENING_SNACK','DINNER']):CommonFood=>({id:`F_${name}`,version:1,canonicalCode:name,canonicalName:name,displayName:name,foodType:'COMMON_FOOD',family:name,category:roles.includes('VEGETABLE')?'vegetable':roles.includes('PULSE')?'legume':roles.includes('DAIRY')?'dairy':'grain',countryContext:'GLOBAL_GENERIC',isIndianSpecificFood:false,sourcePolicyClass:'GLOBAL_GENERIC_APPROVED',sourceMappingId:`S_${name}`,sourceVersion:'1',vegetarianClass:'VEGAN',dietTags:[],allergens:[],intolerances:[],clinicalTags:[],avoidTags:[],mealHeads:heads,roles,nutrientsPer100g:{kcal:120,protein:8,carbohydrate:18,fat:2,fibre:3},servings:[{id:`SV_${name}`,version:1,label:'100 g',grams:100,millilitres:null,unit:'gram',isDefault:true,minMultiplier:1,maxMultiplier:1,allowedMultipliers:[1],active:true}],active:true,clientConsumable:true,generatorEligible:true,aliases:[name]});
const comp=(f:CommonFood):MealComponent=>({componentId:f.id,foodId:f.id,foodVersion:1,foodDisplayNameSnapshot:f.displayName,servingId:f.servings[0].id,servingVersion:1,servingDisplayNameSnapshot:'100 g',multiplier:1,grams:100,millilitres:null,label:'100 g',sourceType:'COMMON_FOOD',sourceMappingId:f.sourceMappingId,nutrition:f.nutrientsPer100g});
const score=(f:CommonFood,usage=emptyDailyFoodUsage(),head:MealHead='LUNCH')=>scoreDayAwareQuality({components:[comp(f)],nutrition:f.nutrientsPer100g,foods:new Map([[f.id,f]]),dailyUsage:usage,mealHead:head,targetKcal:120,targetProtein:8});

test('canonical V3 metadata governs potato, grains, pulses, proteins and flexible chapati',()=>{assert.equal(classifyFoodQuality(make('potato',['VEGETABLE'])).repetitionProfile,'STRICT_ROTATION');assert.equal(classifyFoodQuality(make('brown rice',['GRAIN'])).grainFamily,'RICE');assert.equal(classifyFoodQuality(make('moong dal',['PULSE','PROTEIN'])).pulseFamily,'MOONG');assert.equal(classifyFoodQuality(make('egg',['PROTEIN'])).proteinFamily,'EGG');assert.equal(classifyFoodQuality(make('chapati',['BREAD'])).repetitionProfile,'FLEXIBLE_ROTATION');});
test('strict potato repeat loses more score than flexible chapati repeat',()=>{const p=make('potato',['VEGETABLE']),c=make('chapati',['BREAD']);const pu=emptyDailyFoodUsage(),cu=emptyDailyFoodUsage();pu.foodCounts[p.id]=2;cu.foodCounts[c.id]=2;assert.ok(score(p,pu).exactFoodRepetitionPenalty>score(c,cu).exactFoodRepetitionPenalty);});
test('rice, pulse and protein family reuse receive independent penalties',()=>{const rice=make('brown rice',['GRAIN']),moong=make('moong dal',['PULSE','PROTEIN']),egg=make('egg',['PROTEIN']);const usage=emptyDailyFoodUsage();usage.grainFamilyCounts!.RICE=1;usage.pulseFamilyCounts!.MOONG=1;usage.proteinFamilyCounts!.EGG=1;assert.ok(score(rice,usage).grainFamilyPenalty>0);assert.ok(score(moong,usage).pulseFamilyPenalty>0);assert.ok(score(egg,usage).proteinFamilyPenalty>0);});
test('adjacent repetition is stronger than non-adjacent repetition',()=>{const p=make('potato',['VEGETABLE']),adj=emptyDailyFoodUsage(),far=emptyDailyFoodUsage();adj.previousFoodIds=[p.id];assert.ok(score(p,adj).adjacentMealPenalty>score(p,far).adjacentMealPenalty);});
test('meal appropriateness and Indian balanced pairing are soft ranking factors',()=>{const fruit=make('apple',['FRUIT'],['BREAKFAST','LUNCH']),rice=make('rice',['GRAIN'],['LUNCH']),dal=make('tur dal',['PULSE','PROTEIN'],['LUNCH']),bhindi=make('bhindi',['VEGETABLE'],['LUNCH']);const foods=new Map([fruit,rice,dal,bhindi].map(f=>[f.id,f]));const balanced=scoreDayAwareQuality({components:[rice,dal,bhindi].map(comp),nutrition:{kcal:360,protein:24,carbohydrate:54,fat:6,fibre:9},foods,mealHead:'LUNCH',targetKcal:360,targetProtein:24});const awkward=scoreDayAwareQuality({components:[comp(fruit)],nutrition:fruit.nutrientsPer100g,foods,mealHead:'LUNCH',targetKcal:120,targetProtein:8});assert.ok(balanced.pairingCompatibility>awkward.pairingCompatibility);assert.ok(score(fruit,undefined,'BREAKFAST').mealAppropriateness>score(fruit,undefined,'LUNCH').mealAppropriateness);});
test('major-component overlap detects serving-like near duplicates',()=>{const a=make('rice',['GRAIN']),b=make('dal',['PULSE']);assert.equal(optionSimilarity([comp(a),comp(b)],[comp(a),comp(b)]),1);assert.equal(optionSimilarity([comp(a)],[comp(b)]),0);});
test('V3 generation is deterministic, distinct and V2 remains an exact opt-out',()=>{const foods=[make('rice',['GRAIN']),make('chapati',['BREAD']),make('oats',['GRAIN']),make('moong dal',['PULSE','PROTEIN']),make('masoor dal',['PULSE','PROTEIN']),make('egg',['PROTEIN']),make('bhindi',['VEGETABLE']),make('spinach',['VEGETABLE']),make('cabbage',['VEGETABLE'])];const template={id:'T',version:'1',mealHead:'LUNCH' as const,alternatives:[{roles:[['GRAIN','BREAD'],['PULSE','PROTEIN'],['VEGETABLE']]}]};const input={foods,context:{diet:'NON_VEGETARIAN' as const,allergies:[],intolerances:[],avoids:[],clinicalExclusions:[],dislikes:[],preferences:[]},mealHead:'LUNCH' as const,target:{kcal:360,protein:24,kcalTolerance:100,proteinTolerance:10},template};const a=generateMealCombinations(input),b=generateMealCombinations(input),v2=generateMealCombinations({...input,rankingV3:false});assert.deepEqual(a,b);assert.equal(a.options.length,5);assert.ok(a.options.every(x=>x.rankingVersion==='COMMON_FOOD_RANKING_V3'));assert.ok(v2.options.every(x=>x.rankingVersion==='COMMON_FOOD_RANKING_V2'));for(let i=0;i<a.options.length;i++)for(let j=i+1;j<a.options.length;j++)assert.ok(optionSimilarity(a.options[i].components,a.options[j].components)<1);});
test('shortage remains truthful and safety remains a hard gate',()=>{const unsafe=make('potato',['VEGETABLE'],['LUNCH']);unsafe.allergens=['nightshade'];const r=generateMealCombinations({foods:[unsafe],context:{diet:'VEGETARIAN',allergies:['nightshade'],intolerances:[],avoids:[],clinicalExclusions:[],dislikes:[],preferences:[]},mealHead:'LUNCH',target:{kcal:120,protein:8,kcalTolerance:100,proteinTolerance:10}});assert.equal(r.options.length,0);assert.equal(r.shortage?.missing,5);});
test('day usage tracks exact, family and adjacency in memory without queries',()=>{const rice=make('rice',['GRAIN']),dal=make('moong dal',['PULSE','PROTEIN']);const u=addCombinationToDailyUsage(emptyDailyFoodUsage(),[comp(rice),comp(dal)],new Map([rice,dal].map(f=>[f.id,f])),'LUNCH');assert.equal(u.foodCounts[rice.id],1);assert.equal(u.grainFamilyCounts!.RICE,1);assert.equal(u.pulseFamilyCounts!.MOONG,1);assert.deepEqual(u.previousFoodIds,[rice.id,dal.id]);});
