import assert from 'node:assert/strict';
import test from 'node:test';
import { performance } from 'node:perf_hooks';
import { commonFoodCatalogue, getDayDiversityDiagnostics } from '../../backend/src/modules/nutrition/common-food-consultant.service.js';
import { canonicalFoodIdentity, dedupeCanonicalFoods, DEFAULT_MEAL_TEMPLATES, generateMealCombinations, MEAL_HEADS, optionSemanticFingerprint, type ClientFoodContext, type GeneratedCombination, type MealHead, type MealTarget } from '../../backend/src/modules/nutrition/common-food-engine.js';
import { COMMON_FOOD_DAY_DIVERSITY_VERSION_V5, selectDayDiverseOptions } from '../../backend/src/modules/nutrition/common-food-day-diversity.js';
import { classifyFoodQuality } from '../../backend/src/modules/nutrition/common-food-ranking.js';

const targets:Record<MealHead,MealTarget>={EARLY_MORNING:{kcal:170,protein:10,kcalTolerance:70,proteinTolerance:10},BREAKFAST:{kcal:420,protein:26,kcalTolerance:120,proteinTolerance:15},MID_MORNING:{kcal:190,protein:10,kcalTolerance:80,proteinTolerance:10},LUNCH:{kcal:560,protein:34,kcalTolerance:140,proteinTolerance:18},EVENING_SNACK:{kcal:220,protein:14,kcalTolerance:90,proteinTolerance:12},DINNER:{kcal:470,protein:31,kcalTolerance:130,proteinTolerance:17},BEDTIME:{kcal:130,protein:8,kcalTolerance:60,proteinTolerance:8}};
const contexts:Record<string,ClientFoodContext>={vegetarian:{diet:'VEGETARIAN',allergies:[],intolerances:[],avoids:[],clinicalExclusions:[],dislikes:[],preferences:[]},egg:{diet:'EGG',allergies:[],intolerances:[],avoids:[],clinicalExclusions:[],dislikes:[],preferences:[]},nonVegetarian:{diet:'NON_VEGETARIAN',allergies:[],intolerances:[],avoids:[],clinicalExclusions:[],dislikes:[],preferences:[]}};
const hash=(option:GeneratedCombination)=>option.components.map(component=>component.foodId).sort().join('|');
const family=(foodId:string)=>{const food=commonFoodCatalogue.find(item=>item.id===foodId)!;const quality=classifyFoodQuality(food);return quality.pulseFamily??quality.grainFamily??quality.proteinFamily??quality.vegetableFamily??food.roles[0]??food.category;};
const metrics=(meals:Array<{mealHead:MealHead;options:GeneratedCombination[]}>)=>{const foodHeads=new Map<string,Set<string>>();const foods:string[]=[];const families:string[]=[];let adjacent=0;let previous=new Set<string>();for(const meal of meals){const current=new Set(meal.options.flatMap(option=>option.components.map(component=>component.foodId)));for(const id of current){const heads=foodHeads.get(id)??new Set<string>();heads.add(meal.mealHead);foodHeads.set(id,heads);if(previous.has(id))adjacent++;}previous=current;for(const option of meal.options)for(const component of option.components){foods.push(component.foodId);families.push(family(component.foodId));}}return {selected:meals.reduce((sum,meal)=>sum+meal.options.length,0),uniqueFoods:new Set(foods).size,repeatedExact:foods.length-new Set(foods).size,repeatedFamilies:families.length-new Set(families).size,repeatedCombinations:meals.flatMap(meal=>meal.options.map(hash)).length-new Set(meals.flatMap(meal=>meal.options.map(hash))).size,adjacent,dominant4:[...foodHeads.values()].filter(heads=>heads.size>=4).length};};

const generate=(context:ClientFoodContext,limit:number)=>MEAL_HEADS.map(mealHead=>({mealHead,options:generateMealCombinations({foods:commonFoodCatalogue,context,mealHead,target:targets[mealHead],limit,rankingV3:true,semanticV1:true}).options}));

test('V5 shares bounded diversity state across all seven meal heads deterministically',()=>{for(const [name,context] of Object.entries(contexts)){const beforeStarted=performance.now();const before=generate(context,5);const beforeMs=performance.now()-beforeStarted;const afterStarted=performance.now();const candidates=generate(context,30);const first=selectDayDiverseOptions({foods:commonFoodCatalogue,meals:candidates});const afterMs=performance.now()-afterStarted;const second=selectDayDiverseOptions({foods:commonFoodCatalogue,meals:candidates});assert.equal(first.version,COMMON_FOOD_DAY_DIVERSITY_VERSION_V5);assert.equal(first.meals.length,7,name);assert.deepEqual(first.meals.map(meal=>meal.options.map(hash)),second.meals.map(meal=>meal.options.map(hash)),name);assert.ok(first.meals.every(meal=>meal.options.length===5),name);assert.ok(first.meals.every(meal=>new Set(meal.options.map(hash)).size===5),name);assert.equal(new Set(first.meals.flatMap(meal=>meal.options.map(hash))).size,35,name);const beforeMetrics=metrics(before),afterMetrics=metrics(first.meals);assert.ok(afterMetrics.repeatedExact<beforeMetrics.repeatedExact,`${name}: ${JSON.stringify({beforeMetrics,afterMetrics})}`);assert.ok(afterMetrics.adjacent<=beforeMetrics.adjacent,`${name}: ${JSON.stringify({beforeMetrics,afterMetrics})}`);assert.equal(afterMetrics.dominant4,0,`${name}: ${JSON.stringify(afterMetrics)}`);console.log(`V17_39_METRICS ${JSON.stringify({diet:name,before:{...beforeMetrics,durationMs:Number(beforeMs.toFixed(3))},after:{...afterMetrics,durationMs:Number(afterMs.toFixed(3))}})}`);}}
);

test('all meal heads retain distinct governed suitability templates',()=>{for(const mealHead of MEAL_HEADS){const template=DEFAULT_MEAL_TEMPLATES.find(item=>item.mealHead===mealHead);assert.ok(template);assert.ok(template.alternatives.length>0);for(const alternative of template.alternatives)assert.ok(alternative.roles.every(roles=>roles.length>0));}assert.deepEqual(DEFAULT_MEAL_TEMPLATES.find(item=>item.mealHead==='BEDTIME')!.alternatives.map(item=>item.roles),[[['DAIRY']],[['BEVERAGE']],[['DAIRY'],['NUT_SEED']]]);});

test('meal-pool diagnostics are restricted to admin debug roles',()=>{const account=(role:string)=>({user:{role},accountId:'test'}) as never;assert.throws(()=>getDayDiversityDiagnostics(account('consultant'),'VEGETARIAN'),/ADMIN_AUTHORITY_REQUIRED/);const report=getDayDiversityDiagnostics(account('admin'),'VEGETARIAN');assert.equal(report.meals.length,7);for(const meal of report.meals){assert.ok(meal.catalogueSearchableCount>=meal.operationalEligibleCount);assert.ok(meal.operationalEligibleCount>=meal.generatorEligibleCount);assert.ok(meal.topRankedCandidates.length<=10);assert.equal(meal.finalSelectedOptions.length,5);}});

test('V4 remains inside governed V3 output and is bounded',()=>{const started=performance.now();const candidates=generate(contexts.vegetarian,30);const allowed=new Set(candidates.flatMap(meal=>meal.options.map(option=>option.combinationId)));const result=selectDayDiverseOptions({foods:commonFoodCatalogue,meals:candidates});assert.ok(result.meals.flatMap(meal=>meal.options).every(option=>allowed.has(option.combinationId)));assert.ok(performance.now()-started<2500);});

test('canonical identity and alias-equivalent foods cannot consume separate candidate slots',()=>{const apple=commonFoodCatalogue.find(food=>food.displayName.toLowerCase().includes('apple'))!;const alias={...structuredClone(apple),id:`${apple.id}_ALIAS`,canonicalCode:`${apple.canonicalCode}_ALIAS`,canonicalName:'seb',displayName:'Seb',aliases:[...apple.aliases,'apple']};const deduped=dedupeCanonicalFoods([apple,alias]);assert.equal(deduped.length,1);assert.notEqual(canonicalFoodIdentity(apple),canonicalFoodIdentity(alias));const foods=new Map([[apple.id,apple],[alias.id,alias]]);const component=(food:typeof apple)=>({componentId:food.id,foodId:food.id,foodVersion:1,foodDisplayNameSnapshot:food.displayName,servingId:food.servings[0].id,servingVersion:1,servingDisplayNameSnapshot:food.servings[0].label,multiplier:1,grams:food.servings[0].grams,millilitres:null,label:food.servings[0].label,sourceType:'COMMON_FOOD' as const,sourceMappingId:food.sourceMappingId,nutrition:food.nutrientsPer100g});assert.equal(optionSemanticFingerprint([component(apple)],foods),optionSemanticFingerprint([component(alias)],foods));assert.equal(dedupeCanonicalFoods([apple,alias]).map(food=>food.id).join(','),apple.id);});

test('audited Batch-0 activation identity wins over an older alias projection',()=>{const cucumber=commonFoodCatalogue.find(food=>food.id==='BATCH0_42')!;assert.ok(cucumber);const older={...structuredClone(cucumber),id:'CF_OLDER_CUCUMBER',canonicalCode:'usda 169225'};assert.equal(dedupeCanonicalFoods([older,cucumber]).length,1);assert.equal(dedupeCanonicalFoods([older,cucumber])[0]!.id,'BATCH0_42');assert.equal(dedupeCanonicalFoods([cucumber,older])[0]!.id,'BATCH0_42');});

test('shared regional aliases do not collapse distinct raw and ripe identities',()=>{const raw=commonFoodCatalogue.find(food=>food.id==='BATCH0_57')!;const ripe=commonFoodCatalogue.find(food=>food.id==='BATCH0_133')!;assert.ok(raw);assert.ok(ripe);assert.ok(raw.aliases.includes('kathal'));assert.ok(ripe.aliases.includes('Kathal'));assert.equal(dedupeCanonicalFoods([raw,ripe]).length,2);});

test('full-day V4 performance remains bounded over deterministic cohorts',()=>{const before:number[]=[],after:number[]=[];for(const context of Object.values(contexts))for(let run=0;run<5;run++){let started=performance.now();generate(context,5);before.push(performance.now()-started);started=performance.now();selectDayDiverseOptions({foods:commonFoodCatalogue,meals:generate(context,30)});after.push(performance.now()-started);}const summarize=(values:number[])=>{values.sort((a,b)=>a-b);return {p50Ms:Number(values[Math.ceil(values.length*.5)-1].toFixed(3)),p95Ms:Number(values[Math.ceil(values.length*.95)-1].toFixed(3)),maxMs:Number(values.at(-1)!.toFixed(3))};};const report={samples:after.length,before:summarize(before),after:summarize(after)};console.log(`V17_39_PERFORMANCE ${JSON.stringify(report)}`);assert.ok(report.after.maxMs<2500);});
