import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { commonFoodCatalogue } from '../../backend/src/modules/nutrition/common-food-consultant.service.js';
import { generateMealCombinations, sumNutrition } from '../../backend/src/modules/nutrition/common-food-engine.js';

const read=(path:string)=>readFileSync(new URL(path,import.meta.url),'utf8');
test('v17.3 freezes combination snapshots on submit and projects them through review and client read',()=>{const service=read('../../backend/src/modules/nutrition/nutrition.service.ts');const store=read('../../backend/src/modules/nutrition/nutrition.store.ts');assert.match(service,/freezeCombinationOptionsForLifecycle\(plan.id, version.id\)/);assert.match(store,/commonFoodOptions/);assert.match(service,/type:'COMBINATION'/);assert.doesNotMatch(service,/components:item\.components/);});
test('v17.3 DOCX uses frozen display names, servings and nutrition rather than catalogue lookup',()=>{const doc=read('../../backend/src/modules/nutrition/nutrition.document.ts');assert.match(doc,/version\.commonFoodOptions/);assert.match(doc,/foodDisplayNameSnapshot/);assert.match(doc,/nutrition\?\.kcal/);assert.doesNotMatch(doc,/commonFoodCatalogue/);});
test('v17.3 admin routes are authenticated, role governed, and cover operational metadata',()=>{const routes=read('../../backend/src/modules/admin/admin.routes.ts');const service=read('../../backend/src/modules/admin/common-food-admin.service.ts');for(const value of ['/common-foods',"/common-foods/:foodId/state","/common-foods/:foodId/aliases","/common-foods/:foodId/servings","/common-foods/:foodId/meal-eligibility","/common-foods/:foodId/roles"])assert.ok(routes.includes(value),value);assert.match(service,/ADMIN_AUTHORITY_REQUIRED/);assert.match(service,/common_food_admin_audit/);assert.doesNotMatch(service,/nutrition_per_100g\s*=/);});
test('representative combination nutrition is exact across an immutable JSON snapshot',()=>{const result=generateMealCombinations({foods:commonFoodCatalogue,context:{diet:'VEGETARIAN',allergies:[],intolerances:[],avoids:[],clinicalExclusions:[],dislikes:[],preferences:[]},mealHead:'LUNCH',target:{kcal:500,protein:30,kcalTolerance:100,proteinTolerance:10}});const saved=result.options[0];const reviewed=structuredClone(saved);const published=structuredClone(reviewed);assert.deepEqual(saved.nutrition,sumNutrition(saved.components.map(x=>x.nutrition)));assert.deepEqual(reviewed,saved);assert.deepEqual(published,reviewed);for(const component of saved.components){assert.ok(component.foodDisplayNameSnapshot);assert.ok(component.servingDisplayNameSnapshot);}});
test('v17.3 migration is additive and provides lifecycle snapshot plus admin audit',()=>{const sql=read('../../backend/src/db/migrations/0051_common_food_lifecycle_snapshot.sql');assert.match(sql,/diet_plan_versions add column if not exists common_food_options/);assert.match(sql,/common_food_snapshot_hash/);assert.match(sql,/create table if not exists common_food_admin_audit/);});
