import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { generateMealCombinations, type CommonFood, type MealComponent } from '../../backend/src/modules/nutrition/common-food-engine.js';
import { mealTitle, ontologyFor, validateMealQuality, withSemanticServingProfile } from '../../backend/src/modules/nutrition/common-food-semantics.js';
import { createProductionPreparedFoods } from '../../backend/src/modules/nutrition/prepared-food-production.js';
import { createGovernedCommonFoodPopulation } from '../../backend/src/modules/nutrition/common-food-population.js';
import { deriveVersionedMealTargets } from '../../backend/src/modules/nutrition/calorie-macro-allocation.js';

const food=(name:string,category:string,roles:CommonFood['roles'],grams=100):CommonFood=>({id:`F_${name}`,version:1,canonicalCode:name,canonicalName:name,displayName:name,foodType:'COMMON_FOOD',family:name,category,countryContext:'GLOBAL_GENERIC',isIndianSpecificFood:false,sourcePolicyClass:'GLOBAL_GENERIC_APPROVED',sourceMappingId:`S_${name}`,sourceVersion:'1',vegetarianClass:'VEGAN',dietTags:[],allergens:[],intolerances:[],clinicalTags:[],avoidTags:[],mealHeads:['EARLY_MORNING','BREAKFAST','MID_MORNING','LUNCH','EVENING_SNACK','DINNER','BEDTIME'],roles,nutrientsPer100g:{kcal:100,protein:5,carbohydrate:15,fat:2,fibre:2},servings:[{id:`SV_${name}`,version:1,label:`${grams} g`,grams,millilitres:null,unit:'gram',isDefault:true,minMultiplier:.5,maxMultiplier:2,allowedMultipliers:[.5,1,1.5,2],active:true}],active:true,clientConsumable:true,generatorEligible:true,aliases:[name]});
const component=(f:CommonFood,grams=f.servings[0].grams):MealComponent=>({componentId:f.id,foodId:f.id,foodVersion:1,foodDisplayNameSnapshot:f.displayName,servingId:f.servings[0].id,servingVersion:1,servingDisplayNameSnapshot:f.servings[0].label,multiplier:grams/f.servings[0].grams,grams,millilitres:null,label:f.servings[0].label,sourceType:'COMMON_FOOD',sourceMappingId:f.sourceMappingId,nutrition:{...f.nutrientsPer100g}});
const target={kcal:300,protein:15,kcalTolerance:100,proteinTolerance:8};

test('ontology separates raw ingredients, condiments, toppings, proteins and vegetables',()=>{assert.equal(ontologyFor(food('Wheat flour','grain',['GRAIN'])).ingredientOnly,true);assert.equal(ontologyFor(food('Lemon','fruit',['FRUIT'])).entityType,'CONDIMENT');assert.equal(ontologyFor(food('Ground flaxseed','seeds',['NUT_SEED'])).entityType,'TOPPING');assert.equal(ontologyFor(food('Firm tofu','protein',['PROTEIN'])).primaryRole,'PROTEIN');assert.equal(ontologyFor(food('Paneer','dairy',['DAIRY','PROTEIN'])).primaryRole,'PROTEIN');assert.equal(ontologyFor(food('Bhindi','vegetable',['VEGETABLE'])).primaryRole,'VEGETABLE');});
test('serving intelligence constrains lemon, flaxseed and cooking fat',()=>{assert.ok(ontologyFor(food('Lemon','fruit',['FRUIT'])).serving.maxGrams<100);assert.ok(ontologyFor(food('Ground flaxseed','seeds',['NUT_SEED'])).serving.maxGrams<=20);assert.ok(ontologyFor(food('Cooking oil','oil',['FAT'])).serving.maxGrams<=10);});
test('anti-garbage gate blocks raw flour, 100 g lemon, 100 g flaxseed and primary oil',()=>{for(const f of [food('Wheat flour','grain',['GRAIN']),food('Lemon','fruit',['FRUIT']),food('Ground flaxseed','seeds',['NUT_SEED']),food('Cooking oil','oil',['FAT'])]){const q=validateMealQuality({components:[component(f)],foods:new Map([[f.id,f]]),mealHead:'MID_MORNING',nutrition:{kcal:100,protein:5,carbohydrate:15,fat:2,fibre:2},target:{...target,kcal:100}});assert.equal(q.eligible,false,f.displayName);}});
test('hard calorie mismatch and incomplete main meal fail closed',()=>{const fruit=food('Apple','fruit',['FRUIT']);const q=validateMealQuality({components:[component(fruit)],foods:new Map([[fruit.id,fruit]]),mealHead:'LUNCH',nutrition:{kcal:550,protein:2,carbohydrate:120,fat:1,fibre:4},target:{kcal:210,protein:10,kcalTolerance:50,proteinTolerance:5}});assert.equal(q.calories,'HARD_REJECT');assert.equal(q.structure,'INCOMPLETE');assert.equal(q.eligible,false);});
test('balanced main meal receives structured title without raw option labels',()=>{const rice=food('Cooked rice','grain',['GRAIN']),dal=food('Cooked lentils','legume',['PULSE','PROTEIN']),bhindi=food('Bhindi Sabji','vegetable',['VEGETABLE']);const foods=new Map([rice,dal,bhindi].map(f=>[f.id,f]));const components=[rice,dal,bhindi].map(f=>component(f));const q=validateMealQuality({components,foods,mealHead:'LUNCH',nutrition:{kcal:300,protein:15,carbohydrate:45,fat:5,fibre:8},target});assert.equal(q.structure,'COMPLETE');assert.equal(q.eligible,true,JSON.stringify(q));assert.equal(mealTitle(components,foods),'Cooked rice + Cooked lentils + Bhindi Sabji');assert.doesNotMatch(mealTitle(components,foods),/Option|Generated Combination/);});
test('semantic generation reports truthful shortage rather than padding garbage',()=>{const lemon=food('Lemon','fruit',['FRUIT']);const r=generateMealCombinations({foods:[lemon],context:{diet:'VEGETARIAN',allergies:[],intolerances:[],avoids:[],clinicalExclusions:[],dislikes:[],preferences:[]},mealHead:'EARLY_MORNING',target:{kcal:100,protein:2,kcalTolerance:50,proteinTolerance:3},semanticV1:true});assert.equal(r.options.length,0);assert.equal(r.shortage?.missing,5);assert.ok(r.rejectedBySemanticGate!>0);});
test('interactive editing keeps role-safe replacement and lock-aware auto-balance server-side',()=>{const service=readFileSync(new URL('../../backend/src/modules/nutrition/common-food-consultant.service.ts',import.meta.url),'utf8');const routes=readFileSync(new URL('../../backend/src/modules/nutrition/nutrition.routes.ts',import.meta.url),'utf8');assert.match(service,/COMPONENT_ROLE_MISMATCH/);assert.match(service,/lockedFoodIds/);assert.match(service,/allowedMultipliers/);assert.match(routes,/\/auto-balance/);assert.match(routes,/lockedFoodIds:z\.array/);});
test('production activation is an exact three-release hash-verified overlay',()=>{const active=createProductionPreparedFoods();assert.deepEqual(active.map(x=>x.canonicalCode).sort(),['CP_BHINDI_ALOO','CP_BHINDI_SABJI','CP_CHAPATI']);assert.ok(active.every(x=>x.foodType==='VALIDATED_RECIPE'&&x.active&&x.clientConsumable&&x.generatorEligible&&x.sourceMappingId.includes('VALIDATION_RELEASE:')));assert.equal(active.some(x=>/MOONG|POHA/.test(x.canonicalCode)),false);const chapati=active.find(x=>x.canonicalCode==='CP_CHAPATI')!;assert.equal(chapati.servings[0].label,'1 Chapati');assert.deepEqual(chapati.servings[0].allowedMultipliers,[1,2,3]);});
test('semantic serving adapter turns a reference-basis nut into a realistic exact gram serving',()=>{const almonds=withSemanticServingProfile(food('Roasted almonds','nuts',['NUT_SEED','PROTEIN']));assert.equal(almonds.servings[0].grams,20);assert.equal(almonds.servings[0].label,'20 g');assert.equal(ontologyFor(almonds).serving.maxGrams,40);});
test('v17.23 serving intelligence exposes human labels without changing canonical nutrient basis',()=>{const milk=withSemanticServingProfile(food('Whole milk','dairy',['DAIRY','BEVERAGE']));const fruit=withSemanticServingProfile(food('Papaya','fruit',['FRUIT']));assert.match(milk.servings[0].label,/glass/i);assert.match(fruit.servings[0].label,/medium/i);assert.deepEqual(milk.nutrientsPer100g,food('Whole milk','dairy',['DAIRY','BEVERAGE']).nutrientsPer100g);});
test('2,101 kcal and 131 g supported profiles produce exact semantic 5x7 coverage',()=>{const catalogue=JSON.parse(readFileSync(new URL('../../backend/src/modules/nutrition/catalogue/data/fiteatsy-nutrition-catalogue-v1.1.json',import.meta.url),'utf8'));const foods=[...createGovernedCommonFoodPopulation(catalogue.foods),...createProductionPreparedFoods()].map(withSemanticServingProfile);const targets=deriveVersionedMealTargets({calories:2101,proteinGrams:131});const targetKeys={EARLY_MORNING:'earlyMorning',BREAKFAST:'breakfast',MID_MORNING:'midMorningSnack',LUNCH:'lunch',EVENING_SNACK:'eveningSnack',DINNER:'dinner',BEDTIME:'bedtimeNutrition'} as const;for(const diet of ['VEGETARIAN','EGG','NON_VEGETARIAN'] as const){for(const [mealHead,key] of Object.entries(targetKeys) as Array<[keyof typeof targetKeys,typeof targetKeys[keyof typeof targetKeys]]>){const target=targets[key],result=generateMealCombinations({foods,context:{diet,allergies:[],intolerances:[],avoids:[],clinicalExclusions:[],dislikes:[],preferences:[]},mealHead,target:{kcal:target.calories!,protein:target.proteinGrams!,kcalTolerance:(target.caloriesBand.max!-target.caloriesBand.min!)/2,proteinTolerance:(target.proteinBand.max!-target.proteinBand.min!)/2},semanticV1:true});assert.equal(result.options.length,5,`${diet}:${mealHead}`);}}});
