import assert from 'node:assert/strict';import fs from 'node:fs';import test from 'node:test';
import { authorableCommonFoods, eligibleCommonFoods, type CommonFood } from '../../backend/src/modules/nutrition/common-food-engine.js';
import { similarity } from '../../backend/src/modules/nutrition/food-proposals.service.js';
const context={diet:'VEGETARIAN' as const,allergies:[],intolerances:[],avoids:[],clinicalExclusions:[],dislikes:[],preferences:[]};
const food={id:'approved',version:1,canonicalCode:'APPROVED_1',canonicalName:'chapati',displayName:'Chapati',foodType:'COMMON_FOOD' as const,family:'wheat',category:'grain',countryContext:'INDIA',isIndianSpecificFood:true,sourcePolicyClass:'INDIA_AUTHORITATIVE' as const,sourceMappingId:'approved',sourceVersion:'1',vegetarianClass:'VEGETARIAN' as const,dietTags:[],allergens:[],intolerances:[],clinicalTags:[],avoidTags:[],mealHeads:[],roles:[],nutrientsPer100g:{kcal:300,protein:10,carbohydrate:60,fat:2,fibre:null},servings:[{id:'s',version:1,label:'100 g',grams:100,millilitres:null,unit:'gram',isDefault:true,minMultiplier:.1,maxMultiplier:10,allowedMultipliers:[1],active:true}],active:true,clientConsumable:false,generatorEligible:false,aliases:['roti']} satisfies CommonFood;
test('approved generator-ineligible, clientConsumable-false, off-template food is manual-only',()=>{assert.equal(authorableCommonFoods([food],context).length,1);assert.equal(eligibleCommonFoods([food],context,'LUNCH').length,0)});
test('similarity detects canonical, alias and token variants without auto-merging',()=>{const rows=similarity('Homemade Roti',[{id:'1',canonicalName:'Chapati',aliases:['Whole Wheat Roti'],category:'grain'}]);assert.equal(rows[0].id,'1');assert.ok(rows[0].score>0);assert.equal(rows.length,1)});
test('proposal migration is additive, immutable, audited and matches canonical text user IDs',()=>{const sql=fs.readFileSync(new URL('../../backend/src/db/migrations/0067_consultant_food_proposals.sql',import.meta.url),'utf8');for(const value of ['consultant_food_proposals','consultant_approved_foods','consultant_food_aliases','consultant_food_proposal_audit','PENDING_REVIEW','CHANGE_REQUESTED','source_proposal_id'])assert.match(sql,new RegExp(value));for(const column of ['proposed_by','reviewed_by','approved_by','actor_id'])assert.match(sql,new RegExp(`${column} text(?: not null)? references users\\(id\\)`));assert.doesNotMatch(sql,/(proposed_by|reviewed_by|approved_by|actor_id) uuid/);assert.doesNotMatch(sql,/drop table|truncate/i)});
test('proposal routes preserve null nutrients and all Senior decisions',()=>{const source=fs.readFileSync(new URL('../../backend/src/modules/nutrition/nutrition.routes.ts',import.meta.url),'utf8');for(const value of ['APPROVE_AS_NEW','REJECT_AS_DUPLICATE','USE_EXISTING','LINK_ALIAS','REQUEST_CHANGES','.nullable()','/food-proposals/:id/review'])assert.ok(source.includes(value),value)});
