import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import artifact from '../../backend/src/modules/nutrition/food-curation/data/food_reference_reconciliation_v17_36.json' with {type:'json'};
import report from '../../backend/src/modules/nutrition/food-curation/data/food_reference_catalogue_335_v17_36.json' with {type:'json'};
import {commonFoodCatalogue} from '../../backend/src/modules/nutrition/common-food-consultant.service.js';

test('v17.36 accounts for the exact frozen 128 cohort with zero unprocessed',()=>{assert.equal(artifact.startingCohortCount,128);assert.equal(artifact.decisions.length,128);assert.equal(new Set(artifact.decisions.map(x=>x.referenceItemId)).size,128);assert.equal(artifact.decisions[0].referenceItemId,'BATCH0_183');assert.equal(artifact.finalUnprocessedCount,0);assert.deepEqual(artifact.decisionCounts,{RECIPE_OR_PREPARATION_IDENTITY:27,INGREDIENT_ONLY:49,EXISTING_GOVERNED_RUNTIME_IDENTITY:4,SECONDARY_ONLY:44,ALIAS_EXISTING:4,DUPLICATE_REFERENCE:0,GOVERNED_PARENT_MAPPING:0,NEW_MAPPING:0,INDIA_LAB_VALIDATION_REQUIRED:0});});
test('mapped identities resolve to exact runtime IDs without duplicate source or alias decisions',()=>{const runtime=new Map(commonFoodCatalogue.map(x=>[x.id,x]));const mapped=artifact.decisions.filter(x=>x.runtimeFoodId);assert.equal(mapped.length,8);for(const d of mapped){const food=runtime.get(d.runtimeFoodId!);assert.ok(food,d.referenceItemId);assert.equal(food!.sourceMappingId,d.sourceMappingId);assert.ok(d.finalStatus==='EXISTING_GOVERNED_RUNTIME_IDENTITY'||d.finalStatus==='ALIAS_EXISTING');}assert.equal(new Set(mapped.map(x=>`${x.referenceItemId}:${x.sourceMappingId}`)).size,mapped.length);assert.equal(new Set(artifact.decisions.filter(x=>x.aliasTarget).map(x=>`${x.referenceCanonicalName.toLowerCase()}:${x.aliasTarget}`)).size,4);});
test('identity state portion and activation gates fail closed',()=>{for(const d of artifact.decisions){assert.ok(d.referenceState);assert.equal(d.ediblePortion,'AS_CATALOGUED_EDIBLE_PORTION');assert.equal(d.botanicalIdentity,null);if(!d.runtimeFoodId){assert.equal(d.generatorEligible,false);assert.equal(d.clientConsumable,false);assert.equal(d.sourceMappingId,null);}}assert.equal(artifact.decisions.filter(x=>x.finalStatus==='NEW_MAPPING').length,0);});
test('India-first rights policy and NABL fallback are explicit',()=>{for(const d of artifact.decisions.filter(x=>x.finalStatus==='INDIA_LAB_VALIDATION_REQUIRED')){assert.equal(d.sourceChecks[0].source,'ICMR_NIN_IFCT_RIGHTS_GATE');assert.equal(d.sourceChecks.at(-1)?.source,'USDA_APPROVED_GENERIC');assert.equal(d.requiredAnalytes.length,7);assert.match(d.nablTestRequirement,/NABL ISO\/IEC 17025/);assert.match(d.expectedEvidenceArtifact,/SIGNED_NABL_SCOPE_REPORT/);}});
test('full 335 report is unique and relates every reference to runtime or explicit disposition',()=>{assert.equal(report.referenceCount,335);assert.equal(report.rows.length,335);assert.equal(new Set(report.rows.map(x=>x.referenceItemId)).size,335);assert.ok(report.rows.every(x=>x.finalReferenceStatus&&x.evidenceStatus&&x.operationalUse));});
test('migration and importer enforce transactional idempotent persistence',()=>{const migration=readFileSync(new URL('../../backend/src/db/migrations/0063_food_reference_reconciliation_v17_36.sql',import.meta.url),'utf8');const importer=readFileSync(new URL('../../backend/scripts/import-food-reference-reconciliation-v17-36.ts',import.meta.url),'utf8');assert.match(importer,/pg_advisory_xact_lock/);assert.match(importer,/on conflict\(reference_item_id\) do update/);assert.match(importer,/begin/);assert.match(importer,/commit/);assert.match(migration,/reference_item_id text not null unique/);assert.match(migration,/source_unique/);assert.match(migration,/alias_unique/);});
