import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import test from 'node:test';
const artifactPath = new URL('../../backend/src/modules/nutrition/food-curation/data/p0_food_verification_v17_29.json', import.meta.url);
const artifact = JSON.parse(readFileSync(artifactPath, 'utf8')) as { schemaVersion:string; decisionCount:number; activationCount:number; sourceMappingCount:number; decisions:Array<{referenceItemId:string;outcome:string;generatorEligible:boolean;componentEligible:boolean;sourceMapping:unknown;canonicalName:string;aliases:string[]}> };
const allowed = new Set(['ACTIVATED_GENERATOR','ACTIVATED_COMPONENT_ONLY','SOURCE_MAPPED_NOT_GENERATOR','SOURCE_FOUND_STATE_MISMATCH','SERVING_PROFILE_INCOMPLETE','ONTOLOGY_ROLE_INCOMPLETE','PREPARED_PROVENANCE_REQUIRED','EXTERNAL_SOURCE_REQUIRED','NOT_SUITABLE_FOR_GENERATOR']);
test('v17.30A has exactly one governed decision for every P0 reference identity',()=>{assert.equal(artifact.schemaVersion,'FITEATSY_P0_FOOD_VERIFICATION_V17_30A');assert.equal(artifact.decisionCount,207);assert.equal(artifact.decisions.length,207);assert.equal(new Set(artifact.decisions.map(d=>d.referenceItemId)).size,207);assert.ok(artifact.decisions.every(d=>allowed.has(d.outcome)))});
test('v17.30A activates only exact approved generic source mappings',()=>{assert.equal(artifact.activationCount,19);assert.equal(artifact.sourceMappingCount,21);assert.equal(artifact.decisions.filter(d=>d.generatorEligible).length,10);assert.ok(artifact.decisions.filter(d=>d.generatorEligible||d.componentEligible).every(d=>d.sourceMapping!==null));for(const food of ['Fenugreek leaves','Bottle gourd','Rajma','Sorghum','Pearl millet','Finger millet'])assert.ok(artifact.decisions.some(d=>`${d.canonicalName} ${d.aliases.join(' ')}`.includes(food)&&d.outcome==='EXTERNAL_SOURCE_REQUIRED'),food);assert.match(createHash('sha256').update(readFileSync(artifactPath)).digest('hex'),/^[a-f0-9]{64}$/)});
