import type { HealthObservationRecord } from '../health/health-observations.repository.js';
import { HEALTH_INTELLIGENCE_VERSION } from '@fiteatsy/health-intelligence';
export const METRIC_REGISTRY={steps:{unit:'count',aggregation:'SUM',freshHours:36},distance:{unit:'m',aggregation:'SUM',freshHours:36},active_energy:{unit:'kcal',aggregation:'SUM',freshHours:36},active_minutes:{unit:'min',aggregation:'SUM',freshHours:36},workout_minutes:{unit:'min',aggregation:'SUM',freshHours:36},sleep_minutes:{unit:'min',aggregation:'SUM',freshHours:36},sleep_deep_minutes:{unit:'min',aggregation:'SUM',freshHours:36},sleep_rem_minutes:{unit:'min',aggregation:'SUM',freshHours:36},sleep_awake_minutes:{unit:'min',aggregation:'SUM',freshHours:36},heart_rate:{unit:'bpm',aggregation:'AVERAGE',freshHours:36},resting_heart_rate:{unit:'bpm',aggregation:'AVERAGE',freshHours:36},hrv_sdnn_ms:{unit:'ms',aggregation:'AVERAGE',freshHours:36},hrv_rmssd_ms:{unit:'ms',aggregation:'AVERAGE',freshHours:36},spo2:{unit:'pct',aggregation:'AVERAGE',freshHours:36},respiratory_rate:{unit:'brpm',aggregation:'AVERAGE',freshHours:36},weight:{unit:'kg',aggregation:'LATEST',freshHours:168},hydration_ml:{unit:'ml',aggregation:'SUM',freshHours:36},mindfulness_minutes:{unit:'min',aggregation:'SUM',freshHours:36},stress_score:{unit:'score',aggregation:'LATEST',freshHours:168}} as const;
export type DailyAggregate={date:string;metric:string;value:number;unit:string;method:string;observationIds:string[];freshness:'CURRENT'|'STALE'};
const day=(iso:string,offset=330)=>new Date(Date.parse(iso)+offset*60000).toISOString().slice(0,10);
export const aggregateDaily=(observations:HealthObservationRecord[],now=Date.now()):DailyAggregate[]=>{
 const groups=new Map<string,HealthObservationRecord[]>();
 for(const o of observations){if(!(o.metricType in METRIC_REGISTRY)||o.deletedAtISO)continue;const key=`${day(o.measuredAtISO,o.timezoneOffsetMinutes??330)}|${o.metricType}`;groups.set(key,[...(groups.get(key)??[]),o]);}
 return [...groups.entries()].map(([key,items])=>{const [,metric]=key.split('|');const rule=METRIC_REGISTRY[metric as keyof typeof METRIC_REGISTRY];const sorted=[...items].sort((a,b)=>b.measuredAtISO.localeCompare(a.measuredAtISO));
  const bySource=new Map<string,HealthObservationRecord[]>();for(const item of items){const source=typeof item.sourceMetadata?.sourceApplication==='string'?item.sourceMetadata.sourceApplication:item.sourceProvider;bySource.set(source,[...(bySource.get(source)??[]),item]);}
  const preferred=rule.aggregation==='SUM'?[...[...bySource.values()].sort((a,b)=>b.reduce((s,o)=>s+o.value,0)-a.reduce((s,o)=>s+o.value,0))[0]]:items;
  const value=rule.aggregation==='SUM'?preferred.reduce((s,o)=>s+o.value,0):rule.aggregation==='AVERAGE'?items.reduce((s,o)=>s+o.value,0)/items.length:sorted[0].value;
  return {date:key.slice(0,10),metric,value:Number(value.toFixed(4)),unit:rule.unit,method:rule.aggregation,observationIds:preferred.map(o=>o.id),freshness:now-Date.parse(sorted[0].measuredAtISO)<=rule.freshHours*3600000?'CURRENT':'STALE'};});
};
export const baseline=(rows:DailyAggregate[],metric:string,today:string)=>{const eligible=rows.filter(r=>r.metric===metric&&r.date<=today).sort((a,b)=>b.date.localeCompare(a.date));const avg=(n:number)=>{const v=eligible.slice(0,n);return v.length?v.reduce((s,r)=>s+r.value,0)/v.length:null;};const current=eligible.find(r=>r.date===today)?.value??null,b7=avg(7),b28=avg(28);return {today:current,sevenDayAverage:b7,twentyEightDayBaseline:b28,trend:current!=null&&b7!=null?current-b7:null,deviation:current!=null&&b28!=null?current-b28:null,calculationVersion:HEALTH_INTELLIGENCE_VERSION};};
