import { Router, type NextFunction, type Request, type Response } from 'express';
import { z } from 'zod';
import { getAuthenticatedAccount, requireAuthenticatedAccount } from '../auth/auth.middleware.js';
import { env } from '../../config/env.js';
import { renderHealthSyncLabPage } from './health-sync-lab.page.js';
import {
  HEALTH_SYNC_METRICS, auditDiagnosticAccess, createSyncRequest, getDiagnosticStatus, getMetricRecords, getSyncRequest,
  listDiagnosticDevices, listLocalDiagnosticContexts, listMetricDiagnostics, listPendingDeviceRequests, listQueue,
  resolveLocalDiagnosticContext,
  recordDeviceProgress, recordDeviceSnapshot
} from './health-sync-lab.repository.js';

export const healthSyncLabRouter=Router();
export const healthSyncLabPageRouter=Router();

const internalRoles=new Set(['admin','super_admin','platform_owner']);
const requireInternalRole=(req:Request,res:Response,next:NextFunction)=>{
  const role=String(getAuthenticatedAccount(req).user.role??'').toLowerCase();
  if(!internalRoles.has(role)) return res.status(403).json({error:'INTERNAL_HEALTH_SYNC_ROLE_REQUIRED',message:'Internal health-sync diagnostics authority is required.'});
  return next();
};
const query=z.object({accountId:z.string().min(1),connectionId:z.string().min(1).optional()});
const handle=(res:Response,error:unknown)=>res.status(500).json({error:'HEALTH_SYNC_DIAGNOSTIC_FAILED',message:error instanceof Error?error.message:'Diagnostic request failed.'});

const loopbackHosts=new Set(['127.0.0.1','localhost','::1','::ffff:127.0.0.1']);
export const isLocalHealthLabRequest=(req:Pick<Request,'hostname'|'socket'>)=>{
  const hostname=String(req.hostname??'').toLowerCase();
  const localAddress=String(req.socket?.localAddress??'').toLowerCase();
  return env.localHealthLabEnabled
    && ['development','local','test'].includes(String(env.environment).toLowerCase())
    && loopbackHosts.has(hostname)
    && loopbackHosts.has(localAddress);
};
const requireLocalHealthLab=(req:Request,res:Response,next:NextFunction)=>isLocalHealthLabRequest(req)
  ? next()
  : res.status(403).json({error:'DIAGNOSTIC_LOCAL_ONLY',message:'Local Health Sync Lab requires loopback access and explicit local diagnostic mode.'});

// Local diagnostic mode is a separate loopback-only adapter. The governed
// authenticated routes below remain unchanged for non-local environments.
healthSyncLabPageRouter.get('/health-sync-lab',requireLocalHealthLab,(_req,res)=>res.type('html').send(renderHealthSyncLabPage()));

healthSyncLabRouter.get('/local/contexts',requireLocalHealthLab,async(_req,res)=>{try{return res.json({items:await listLocalDiagnosticContexts(),backendCommitSha:env.gitCommit});}catch(e){return handle(res,e)}});
healthSyncLabRouter.get('/local/snapshot',requireLocalHealthLab,async(req,res)=>{const connectionId=z.string().min(1).safeParse(req.query.connectionId);if(!connectionId.success)return res.status(400).json({error:'INVALID_INPUT'});try{const context=await resolveLocalDiagnosticContext(connectionId.data);if(!context)return res.status(404).json({error:'DEVICE_NOT_FOUND'});const [status,metrics,queue]=await Promise.all([getDiagnosticStatus(context.account_id,context.connection_id),listMetricDiagnostics(context.account_id,context.connection_id),listQueue(context.account_id,context.connection_id)]);if(!status)return res.status(404).json({error:'DEVICE_NOT_FOUND'});await auditDiagnosticAccess({actorId:context.account_id,targetAccountId:context.account_id,connectionId:context.connection_id,eventType:'VIEW_DIAGNOSTICS',safeMetadata:{mode:'LOCAL_LOOPBACK'}});return res.json({context,status:{...status,backendCommitSha:env.gitCommit},metrics:{items:metrics},queue});}catch(e){return handle(res,e)}});
healthSyncLabRouter.post('/local/requests',requireLocalHealthLab,async(req,res)=>{const parsed=z.object({connectionId:z.string().min(1),metrics:z.array(z.union([z.enum(HEALTH_SYNC_METRICS),z.literal('ALL_SUPPORTED')])).min(1).default(['ALL_SUPPORTED'])}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'INVALID_INPUT'});try{const context=await resolveLocalDiagnosticContext(parsed.data.connectionId);if(!context)return res.status(404).json({error:'DEVICE_NOT_FOUND'});const value=await createSyncRequest({accountId:context.account_id,clientId:context.client_id,connectionId:context.connection_id,provider:context.provider,metrics:parsed.data.metrics,actorId:context.account_id});return value?res.status(202).json(value):res.status(404).json({error:'ACTIVE_DEVICE_NOT_FOUND'});}catch(e){return handle(res,e)}});

healthSyncLabRouter.get('/devices',requireAuthenticatedAccount,requireInternalRole,async(req,res)=>{const parsed=z.object({accountId:z.string().min(1),clientId:z.string().min(1).optional()}).safeParse(req.query);if(!parsed.success)return res.status(400).json({error:'INVALID_INPUT'});try{await auditDiagnosticAccess({actorId:getAuthenticatedAccount(req).accountId,targetAccountId:parsed.data.accountId,eventType:'VIEW_DIAGNOSTICS'});return res.json({items:await listDiagnosticDevices(parsed.data.accountId,parsed.data.clientId),backendCommitSha:env.gitCommit});}catch(e){return handle(res,e)}});
healthSyncLabRouter.get('/status',requireAuthenticatedAccount,requireInternalRole,async(req,res)=>{const parsed=query.required({connectionId:true}).safeParse(req.query);if(!parsed.success)return res.status(400).json({error:'INVALID_INPUT'});try{const value=await getDiagnosticStatus(parsed.data.accountId,parsed.data.connectionId);return value?res.json({...value,backendCommitSha:env.gitCommit}):res.status(404).json({error:'DEVICE_NOT_FOUND'});}catch(e){return handle(res,e)}});
healthSyncLabRouter.get('/metrics',requireAuthenticatedAccount,requireInternalRole,async(req,res)=>{const parsed=query.required({connectionId:true}).safeParse(req.query);if(!parsed.success)return res.status(400).json({error:'INVALID_INPUT'});try{return res.json({items:await listMetricDiagnostics(parsed.data.accountId,parsed.data.connectionId)});}catch(e){return handle(res,e)}});
healthSyncLabRouter.get('/metrics/:metricId',requireAuthenticatedAccount,requireInternalRole,async(req,res)=>{const parsed=z.object({accountId:z.string().min(1),connectionId:z.string().min(1),limit:z.coerce.number().int().min(1).max(100).default(25)}).safeParse(req.query);const metric=z.enum(HEALTH_SYNC_METRICS).safeParse(req.params.metricId);if(!parsed.success||!metric.success)return res.status(400).json({error:'INVALID_INPUT'});try{await auditDiagnosticAccess({actorId:getAuthenticatedAccount(req).accountId,targetAccountId:parsed.data.accountId,connectionId:parsed.data.connectionId,eventType:'INSPECT_RECORDS',metricType:metric.data});return res.json({items:await getMetricRecords(parsed.data.accountId,parsed.data.connectionId,metric.data,parsed.data.limit)});}catch(e){return handle(res,e)}});
healthSyncLabRouter.get('/queue',requireAuthenticatedAccount,requireInternalRole,async(req,res)=>{const parsed=query.required({connectionId:true}).safeParse(req.query);if(!parsed.success)return res.status(400).json({error:'INVALID_INPUT'});try{return res.json(await listQueue(parsed.data.accountId,parsed.data.connectionId));}catch(e){return handle(res,e)}});
healthSyncLabRouter.post('/requests',requireAuthenticatedAccount,requireInternalRole,async(req,res)=>{const parsed=z.object({accountId:z.string().min(1),clientId:z.string().min(1),connectionId:z.string().min(1),provider:z.enum(['APPLE_HEALTH','HEALTH_CONNECT']),metrics:z.array(z.union([z.enum(HEALTH_SYNC_METRICS),z.literal('ALL_SUPPORTED')])).min(1)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'INVALID_INPUT'});try{const value=await createSyncRequest({...parsed.data,actorId:getAuthenticatedAccount(req).accountId});return value?res.status(202).json(value):res.status(404).json({error:'ACTIVE_DEVICE_NOT_FOUND'});}catch(e){return handle(res,e)}});
healthSyncLabRouter.get('/requests/:id',requireAuthenticatedAccount,requireInternalRole,async(req,res)=>{const accountId=z.string().min(1).safeParse(req.query.accountId);if(!accountId.success)return res.status(400).json({error:'INVALID_INPUT'});try{const value=await getSyncRequest(accountId.data,String(req.params.id));return value?res.json(value):res.status(404).json({error:'SYNC_REQUEST_NOT_FOUND'});}catch(e){return handle(res,e)}});

// Native companion endpoints use the authenticated mobile account and cannot inspect another account.
healthSyncLabRouter.get('/mobile/requests',requireAuthenticatedAccount,async(req,res)=>{const connectionId=z.string().min(1).safeParse(req.query.connectionId);if(!connectionId.success)return res.status(400).json({error:'INVALID_INPUT'});const account=getAuthenticatedAccount(req);try{return res.json({items:await listPendingDeviceRequests(account.accountId,connectionId.data)});}catch(e){return handle(res,e)}});
healthSyncLabRouter.post('/mobile/heartbeat',requireAuthenticatedAccount,async(req,res)=>{const account=getAuthenticatedAccount(req);const metric=z.object({metricType:z.enum(HEALTH_SYNC_METRICS),supported:z.boolean(),permissionState:z.enum(['GRANTED','DENIED','NOT_DETERMINED','UNSUPPORTED']),nativeRecordCount:z.number().int().nonnegative(),localRecordCount:z.number().int().nonnegative(),terminalState:z.enum(['IDLE','RUNNING','SUCCESS','NO_DATA','PERMISSION_DENIED','UNSUPPORTED','FAILED','TIMED_OUT']),uploadState:z.enum(['NOT_REQUIRED','PENDING','RUNNING','SUCCESS','PARTIAL','FAILED']),latestNativeAt:z.string().datetime().optional(),latestLocalAt:z.string().datetime().optional(),nativeReadAt:z.string().datetime().optional(),localPersistAt:z.string().datetime().optional(),backendPersistAt:z.string().datetime().optional(),displayReadyAt:z.string().datetime().optional(),sourceOrigin:z.string().max(180).optional(),safeErrorCode:z.string().max(120).optional()});const activityValue=z.object({value:z.number(),goal:z.number(),unit:z.string().max(12)});const activitySummary=z.object({dateISO:z.string().datetime(),move:activityValue,exercise:activityValue,stand:activityValue});const workoutSummary=z.object({count:z.number().int().nonnegative(),latestAtISO:z.string().datetime().nullable(),activityType:z.union([z.string(),z.number()]).nullable(),durationSeconds:z.number().nonnegative().nullable(),energyKcal:z.number().nonnegative().nullable(),distanceMeters:z.number().nonnegative().nullable(),source:z.string().max(80).nullable()});const parsed=z.object({connectionId:z.string().min(1),appVersion:z.string().max(80).optional(),buildNumber:z.string().max(80).optional(),osVersion:z.string().max(80).optional(),mobileCommitSha:z.string().max(80).optional(),deviceLabel:z.string().max(120).optional(),healthKitAvailable:z.boolean().optional(),activitySummary:activitySummary.nullable().optional(),workoutSummary:workoutSummary.nullable().optional(),pendingCount:z.number().int().nonnegative(),failedCount:z.number().int().nonnegative(),quarantinedCount:z.number().int().nonnegative(),persistedDocumentBytes:z.number().int().nonnegative(),nativeHeartbeat:z.boolean(),localPersisted:z.boolean(),uploaded:z.boolean(),metrics:z.array(metric).max(HEALTH_SYNC_METRICS.length)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'INVALID_INPUT'});try{const value=await recordDeviceSnapshot({...parsed.data,accountId:account.accountId,clientId:account.client.id});return value?res.json(value):res.status(404).json({error:'DEVICE_NOT_FOUND'});}catch(e){return handle(res,e)}});
healthSyncLabRouter.post('/mobile/requests/:id/progress',requireAuthenticatedAccount,async(req,res)=>{const account=getAuthenticatedAccount(req);const parsed=z.object({connectionId:z.string().min(1),status:z.enum(['PENDING','ACKNOWLEDGED','RUNNING','SUCCESS','PARTIAL','FAILED','TIMED_OUT','CANCELLED']),eventType:z.enum(['ACKNOWLEDGED','SYNC_STARTED','METRIC_STARTED','METRIC_COMPLETED','LOCAL_PERSISTED','UPLOAD_STARTED','UPLOAD_COMPLETED','SYNC_COMPLETED','SYNC_FAILED']),metric:z.enum(HEALTH_SYNC_METRICS).optional(),safeMetadata:z.record(z.union([z.string(),z.number(),z.boolean(),z.null()])).optional()}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'INVALID_INPUT'});try{const value=await recordDeviceProgress({...parsed.data,requestId:String(req.params.id),accountId:account.accountId,clientId:account.client.id});return value?res.json(value):res.status(404).json({error:'SYNC_REQUEST_NOT_FOUND'});}catch(e){return handle(res,e)}});
