export const renderHealthSyncLabPage = () => `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>FitEatsy Health Sync Lab</title><style>
:root{color-scheme:dark;--bg:#090b0d;--surface:#12161a;--surface2:#1a2026;--border:#303841;--text:#f5f7fa;--muted:#9ba7b4;--green:#30d158;--amber:#ff9f0a;--red:#ff453a;--blue:#0a84ff}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{max-width:1480px;margin:auto;padding:24px}
h1{font-size:28px;margin:0}h2{font-size:18px;margin:0 0 16px}.eyebrow{text-transform:uppercase;letter-spacing:.12em;color:var(--green);font-size:12px}.muted{color:var(--muted)}
.header,.card{background:var(--surface);border:1px solid var(--border);border-radius:18px;padding:20px}.header{display:flex;justify-content:space-between;gap:20px;align-items:center}.controls{display:flex;gap:10px;flex-wrap:wrap}
input,select,button{background:var(--surface2);color:var(--text);border:1px solid var(--border);border-radius:10px;padding:11px 13px}button{cursor:pointer;font-weight:700}button.primary{background:var(--green);border-color:var(--green);color:#061008}
.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin:18px 0}.stat b{font-size:22px;display:block;margin-top:8px}.status{font-weight:700}.SUCCESS,.GRANTED,.CONNECTED,.MATCH{color:var(--green)}.FAILED,.DENIED,.MISMATCH,.TIMED_OUT{color:var(--red)}.RUNNING,.PENDING,.PARTIAL{color:var(--amber)}
.table-wrap{overflow:auto}.card{margin-top:18px}table{width:100%;border-collapse:collapse;min-width:1100px}th,td{text-align:left;padding:12px 10px;border-bottom:1px solid var(--border);white-space:nowrap}th{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.08em}
.pipeline{display:flex;gap:6px}.stage{width:11px;height:11px;border-radius:50%;background:#404851}.stage.done{background:var(--green)}.stage.wait{background:var(--amber)}
.notice{margin:18px 0;padding:13px 16px;border-radius:12px;background:#102116;color:#baf4c7}.error{background:#2a1212;color:#ffb4ae}.hidden{display:none}@media(max-width:850px){main{padding:14px}.grid{grid-template-columns:1fr 1fr}.header{align-items:flex-start;flex-direction:column}}
</style></head><body><main>
<section class="header"><div><div class="eyebrow">Internal diagnostics</div><h1>Native Health Sync Lab</h1><div class="muted">Native provider → local canonical store → backend. No browser-native health access.</div></div><div class="controls"><input id="token" type="password" placeholder="Internal bearer token"><input id="account" placeholder="Account ID"><button id="load" class="primary">Load</button></div></section>
<div id="message" class="notice hidden"></div><section id="content" class="hidden">
<div class="grid"><div class="card stat"><span class="muted">Device</span><b id="device">—</b><span id="platform" class="muted">—</span></div><div class="card stat"><span class="muted">Provider</span><b id="provider">—</b><span id="connection" class="status">—</span></div><div class="card stat"><span class="muted">Pending queue</span><b id="pending">0</b><span id="queueMeta" class="muted">—</span></div><div class="card stat"><span class="muted">Build lineage</span><b id="appVersion">—</b><span id="lineage" class="muted">—</span></div></div>
<section class="card"><div class="controls" style="justify-content:space-between"><div><h2>Metric lifecycle</h2><span class="muted">Green stages: native read / local persist / backend persist / display ready</span></div><button id="sync">Request Sync</button></div><div class="table-wrap"><table><thead><tr><th>Metric</th><th>Support</th><th>Permission</th><th>Native</th><th>Local</th><th>Backend</th><th>Latest native</th><th>Terminal</th><th>Upload</th><th>Parity</th><th>Pipeline</th></tr></thead><tbody id="metrics"></tbody></table></div></section>
<section class="card"><h2>Queue & governed requests</h2><div id="requests" class="muted">No requests</div></section></section>
<script>
const $=id=>document.getElementById(id);let currentDevice=null;let timer=null;
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const auth=()=>({Authorization:'Bearer '+$('token').value.trim()});
async function api(path,options={}){const r=await fetch(path,{...options,headers:{...auth(),'content-type':'application/json',...(options.headers||{})}});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.message||body.error||('HTTP '+r.status));return body}
function msg(text,error=false){$('message').textContent=text;$('message').className='notice'+(error?' error':'')}
const dot=(value)=>'<i class="stage '+(value?'done':'wait')+'"></i>';
async function refresh(){if(!currentDevice)return;const [status,metricData,queue]=await Promise.all([api('/internal/health-sync/status?accountId='+encodeURIComponent($('account').value)+'&connectionId='+currentDevice.id),api('/internal/health-sync/metrics?accountId='+encodeURIComponent($('account').value)+'&connectionId='+currentDevice.id),api('/internal/health-sync/queue?accountId='+encodeURIComponent($('account').value)+'&connectionId='+currentDevice.id)]);
const d=status.device;$('device').textContent=d.device_label||d.installation_id;$('platform').textContent=d.platform+' · heartbeat '+(d.last_app_heartbeat_at||'not reported');$('provider').textContent=d.provider;$('connection').textContent=d.status;$('connection').className='status '+d.status;$('pending').textContent=d.pending_count||0;$('queueMeta').textContent=(d.failed_count||0)+' failed · '+(d.quarantined_count||0)+' quarantined';$('appVersion').textContent=d.app_version||'not reported';$('lineage').textContent=(d.mobile_commit_sha||'mobile SHA unavailable')+' · backend '+status.backendCommitSha;
$('metrics').innerHTML=metricData.items.map(m=>{const parity=Number(m.native_record_count)===Number(m.local_record_count)&&Number(m.local_record_count)===Number(m.backend_record_count)?'MATCH':'MISMATCH';return '<tr><td><button data-metric="'+esc(m.metric_type)+'">'+esc(m.metric_type)+'</button></td><td>'+esc(m.supported?'SUPPORTED':'UNSUPPORTED')+'</td><td class="'+esc(m.permission_state)+'">'+esc(m.permission_state)+'</td><td>'+esc(m.native_record_count)+'</td><td>'+esc(m.local_record_count)+'</td><td>'+esc(m.backend_record_count)+'</td><td>'+esc(m.latest_native_at)+'</td><td class="'+esc(m.terminal_state)+'">'+esc(m.terminal_state)+'</td><td class="'+esc(m.upload_state)+'">'+esc(m.upload_state)+'</td><td class="'+parity+'">'+parity+'</td><td><span class="pipeline">'+dot(m.native_read_at)+dot(m.local_persist_at)+dot(m.backend_persist_at)+dot(m.display_ready_at)+'</span></td></tr>'}).join('');
$('requests').innerHTML=queue.requests.length?queue.requests.map(r=>'<div><b>'+esc(r.id)+'</b> · <span class="'+esc(r.status)+'">'+esc(r.status)+'</span> · '+esc(r.created_at)+'</div>').join(''):'No requests';}
async function load(){try{sessionStorage.setItem('healthLabToken',$('token').value);const data=await api('/internal/health-sync/devices?accountId='+encodeURIComponent($('account').value));if(!data.items.length)throw new Error('No registered native health device for this account.');currentDevice=data.items[0];$('content').classList.remove('hidden');await refresh();msg('Diagnostic snapshot loaded. Values are metadata only.');clearInterval(timer);timer=setInterval(()=>refresh().catch(()=>{}),5000)}catch(e){msg(e.message,true)}}
$('load').onclick=load;$('sync').onclick=async()=>{try{const r=await api('/internal/health-sync/requests',{method:'POST',body:JSON.stringify({accountId:$('account').value,clientId:currentDevice.client_id,connectionId:currentDevice.id,provider:currentDevice.provider,metrics:['ALL_SUPPORTED']})});msg('Sync request '+r.id+' queued for the native app.');await refresh()}catch(e){msg(e.message,true)}};$('token').value=sessionStorage.getItem('healthLabToken')||'';
</script></main></body></html>`;
