import { readFileSync } from 'node:fs';
import crypto from 'node:crypto';
import type { AuthenticatedAccount } from '../auth/auth.repository.js';
import { getRegisteredConsultantClientProfileContext } from '../consultants/consultants.repository.js';
import { getFoodPreferenceProfile } from './food-preferences.service.js';
import { canAccessConsultantNutritionClient, getConsultantLatestDietPlan, NutritionPlanWorkflowError } from './nutrition.service.js';
import { createGovernedCommonFoodPopulation } from './common-food-population.js';
import { canonicalHash } from './food-curation/canonical-food-foundation.js';
import { COMPONENT_ROLES, generateMealCombinations, MEAL_HEADS, validateManualCombination, type ClientFoodContext, type CommonFood, type ComponentRole, type MealHead, type MealTarget } from './common-food-engine.js';
import { addCombinationToDailyUsage, COMMON_FOOD_RANKING_VERSION_V3, emptyDailyFoodUsage } from './common-food-ranking.js';
import { getCombinationOption, listCombinationOptions, recordCommonFoodGeneration, replaceCombinationOptionSelection, saveCombinationOption, type CombinationSnapshot } from './common-food-consultant.repository.js';
import type { CatalogueFood } from './catalogue/catalogue.types.js';
import { COMMON_FOOD_RANKING_V3_ENABLED } from '../../config/common-food-ranking.js';
import { ontologyFor, validateMealQuality } from './common-food-semantics.js';
import { createProductionPreparedFoods } from './prepared-food-production.js';

const catalogue=JSON.parse(readFileSync(new URL('./catalogue/data/fiteatsy-nutrition-catalogue-v1.1.json',import.meta.url),'utf8')) as {foods:CatalogueFood[]};
const foods=[...createGovernedCommonFoodPopulation(catalogue.foods),...createProductionPreparedFoods()];
const sectionByHead:Record<MealHead,string>={EARLY_MORNING:'earlyMorning',BREAKFAST:'breakfast',MID_MORNING:'midMorningSnack',LUNCH:'lunch',EVENING_SNACK:'eveningSnack',DINNER:'dinner',BEDTIME:'bedtimeNutrition'};
const dietMap={vegetarian:'VEGETARIAN',eggetarian:'EGG',non_vegetarian:'NON_VEGETARIAN',vegan:'VEGAN',jain:'VEGETARIAN'} as const;
export class CommonFoodApiError extends Error{constructor(public code:string,public statusCode:number,message=code){super(message)}}
const roleAllowed=(account:AuthenticatedAccount)=>['consultant','senior_consultant','admin','super_admin','platform_owner'].includes(String(account.user.role).toLowerCase());

export async function resolveClientMealGenerationContext(input:{account:AuthenticatedAccount;clientId:string;planId?:string;mealHead?:MealHead}){
  if(!roleAllowed(input.account))throw new CommonFoodApiError('ROLE_NOT_ALLOWED',403);
  if(!await canAccessConsultantNutritionClient(input.clientId,input.account,{allowSeniorAuthority:true}))throw new CommonFoodApiError('CLIENT_ASSIGNMENT_REQUIRED',403);
  const [registered,prefs,latest]=await Promise.all([getRegisteredConsultantClientProfileContext(input.clientId),getFoodPreferenceProfile(input.clientId),getConsultantLatestDietPlan(input.clientId,input.account)]);
  if(!registered)throw new CommonFoodApiError('CLIENT_NOT_FOUND',404);
  if(!latest)throw new CommonFoodApiError('DIET_PLAN_NOT_FOUND',404);
  if(input.planId&&latest.plan.id!==input.planId)throw new CommonFoodApiError('DIET_PLAN_NOT_FOUND',404);
  const p=prefs?.profile; const diet=p?.dietType?dietMap[p.dietType]:'VEGETARIAN';
  const content=latest.version.content; const daily=content.dailyTargets;
  const mealTargets=Object.fromEntries(MEAL_HEADS.map(head=>{const section=(content.mealPlan as unknown as Record<string,{target?:{calories:number|null;proteinGrams:number|null;caloriesBand?:{min:number|null;max:number|null};proteinBand?:{min:number|null;max:number|null}}}>)[sectionByHead[head]];return [head,{kcal:section?.target?.calories??0,protein:section?.target?.proteinGrams??0,kcalTolerance:Math.max(1,((section?.target?.caloriesBand?.max??0)-(section?.target?.caloriesBand?.min??0))/2||50),proteinTolerance:Math.max(1,((section?.target?.proteinBand?.max??0)-(section?.target?.proteinBand?.min??0))/2||10)} satisfies MealTarget]})) as Record<MealHead,MealTarget>;
  const restrictions=p?.restrictions??[];
  const context:ClientFoodContext={diet,allergies:restrictions.filter(x=>/allerg/i.test(x)),intolerances:restrictions.filter(x=>/intoler/i.test(x)),avoids:[...(p?.foodsAvoided??[]),...(p?.avoidedFoodIds??[])],clinicalExclusions:[],dislikes:[...(p?.foodsDisliked??[]),...(p?.dislikedFoodIds??[])],preferences:[...(p?.foodsLiked??[]),...(p?.likedFoodIds??[]),...(p?.cuisines??[])]};
  return {clientId:input.clientId,internalClientId:registered.internalClientId,consultantId:input.account.accountId,plan:latest.plan,planVersion:latest.version,context,dailyTargets:{calories:daily.calories??null,protein:daily.protein??null,carbohydrate:daily.carbohydrates??null,fat:daily.fat??null},mealTargets,supported:diet!=='VEGAN',capability:diet==='VEGAN'?{code:'VEGAN_COMMON_FOOD_ENGINE_V1_NOT_SUPPORTED',reason:'GOVERNED_VEGAN_BEDTIME_SOURCE_REQUIRED'}:{code:'SUPPORTED',reason:null}};
}

export async function searchCommonFoods(account:AuthenticatedAccount,clientId:string,q:{mealHead?:MealHead;search?:string;category?:string;family?:string;componentRole?:ComponentRole;dietClass?:string;proteinMin?:number;proteinMax?:number;caloriesMin?:number;caloriesMax?:number;limit:number;offset:number}){
 const resolved=await resolveClientMealGenerationContext({account,clientId,mealHead:q.mealHead}); const term=(q.search??'').toLowerCase();
 const eligible=foods.filter(f=>f.active&&f.generatorEligible&&f.clientConsumable&&ontologyFor(f).clientFacing&&!f.allergens.some(x=>resolved.context.allergies.includes(x))&&!f.intolerances.some(x=>resolved.context.intolerances.includes(x))&&!f.avoidTags.some(x=>resolved.context.avoids.includes(x))).filter(f=>!q.mealHead||f.mealHeads.includes(q.mealHead)).filter(f=>!term||[f.displayName,f.canonicalName,...f.aliases].some(x=>x.toLowerCase().includes(term))).filter(f=>!q.category||f.category===q.category).filter(f=>!q.family||f.family===q.family).filter(f=>!q.componentRole||f.roles.includes(q.componentRole)).filter(f=>!q.dietClass||f.vegetarianClass===q.dietClass).filter(f=>(q.proteinMin==null||Number(f.nutrientsPer100g.protein)>=q.proteinMin)&&(q.proteinMax==null||Number(f.nutrientsPer100g.protein)<=q.proteinMax)&&(q.caloriesMin==null||Number(f.nutrientsPer100g.kcal)>=q.caloriesMin)&&(q.caloriesMax==null||Number(f.nutrientsPer100g.kcal)<=q.caloriesMax));
 return {items:eligible.slice(q.offset,q.offset+q.limit).map(publicFood),total:eligible.length,limit:q.limit,offset:q.offset,hasMore:q.offset+q.limit<eligible.length};
}
const publicFood=(f:CommonFood)=>({id:f.id,displayName:f.displayName,aliases:f.aliases,category:f.category,family:f.family,roles:f.roles,mealHeads:f.mealHeads,servings:f.servings,nutritionPer100g:f.nutrientsPer100g,ontology:ontologyFor(f)});

export async function generateCommonFoodPlan(account:AuthenticatedAccount,clientId:string,planId:string,mealHeads:MealHead[]){
 const resolved=await resolveClientMealGenerationContext({account,clientId,planId}); if(!resolved.supported)return {...resolved.capability,supported:false}; const started=performance.now(); const runId=crypto.randomUUID(); const meals=[];const dailyUsage=emptyDailyFoodUsage();const foodsById=new Map(foods.map(food=>[food.id,food]));
 for(const mealHead of mealHeads){const result=generateMealCombinations({foods,context:resolved.context,mealHead,target:resolved.mealTargets[mealHead],dailyUsage,rankingV3:COMMON_FOOD_RANKING_V3_ENABLED,semanticV1:true});meals.push({mealHead,target:resolved.mealTargets[mealHead],coverage:result.shortage??{state:'COMPLETE',available:result.options.length,required:5,missing:0},options:result.options.map(o=>({...o,optionHash:canonicalHash(o)}))});if(result.options[0])addCombinationToDailyUsage(dailyUsage,result.options[0].components,foodsById,mealHead);await recordCommonFoodGeneration({id:`${runId}:${mealHead}`,clientId:resolved.internalClientId,consultantId:resolved.consultantId,inputHash:result.inputHash,candidateCount:result.candidateCount,eligibleCount:result.eligibleFoodCount,options:result.options,shortages:result.shortage,durationMs:performance.now()-started});}
 return {generationRunId:runId,generatorVersion:'COMMON_FOOD_COMBINATION_ENGINE_V1',rankingVersion:COMMON_FOOD_RANKING_V3_ENABLED?COMMON_FOOD_RANKING_VERSION_V3:'COMMON_FOOD_RANKING_V2',templateVersion:'INDIA_COMMON_MEAL_TEMPLATES_V2',catalogueVersion:'NUTRITION_CATALOGUE_V1_1',planVersionId:resolved.planVersion.id,meals};
}

const governedValidationError = (error: unknown): never => {
  const code = error instanceof Error ? error.message : '';
  if (code === 'UNSAFE_OR_INELIGIBLE_FOOD') {
    throw new CommonFoodApiError(code, 422, 'The selected food is not eligible for this client and meal.');
  }
  if (code === 'SERVING_NOT_FOUND') {
    throw new CommonFoodApiError(code, 422, 'The selected serving is not governed for this food.');
  }
  if (code === 'INVALID_SERVING_MULTIPLIER') {
    throw new CommonFoodApiError(code, 422, 'The selected serving multiplier is outside the governed range.');
  }
  if (code === 'INVALID_MEAL_TEMPLATE') {
    throw new CommonFoodApiError(code, 422, 'The selected components do not satisfy the governed meal template.');
  }
  throw error;
};

export async function validateCommonFoodOption(account:AuthenticatedAccount,clientId:string,planId:string,input:{mealHead:MealHead;components:Array<{foodId:string;servingId:string;multiplier:number}>}){const r=await resolveClientMealGenerationContext({account,clientId,planId,mealHead:input.mealHead});if(!r.supported)throw new CommonFoodApiError(r.capability.code,422,r.capability.reason!);try{const option=validateManualCombination({foods,context:r.context,mealHead:input.mealHead,components:input.components,target:r.mealTargets[input.mealHead]});const quality=validateMealQuality({components:option.components,foods:new Map(foods.map(food=>[food.id,food])),mealHead:input.mealHead,nutrition:option.nutrition,target:r.mealTargets[input.mealHead]});if(!quality.eligible)throw new CommonFoodApiError('MEAL_QUALITY_SANITY_FAILED',422,quality.reasons.join(', '));return {...option,mealQuality:quality,mealHead:input.mealHead,optionHash:option.snapshotHash,planVersionId:r.planVersion.id};}catch(error){return governedValidationError(error);}}

export async function persistValidatedOption(account:AuthenticatedAccount,clientId:string,planId:string,input:{optionId?:string;expectedPlanVersionId:string;mealHead:MealHead;components:Array<{foodId:string;servingId:string;multiplier:number}>}){const validated=await validateCommonFoodOption(account,clientId,planId,input);if(validated.planVersionId!==input.expectedPlanVersionId)throw new CommonFoodApiError('STALE_PLAN_VERSION',409);const logicalOptionId=input.optionId??crypto.randomUUID();const prior=input.optionId?await getCombinationOption(input.optionId,planId):null;const snapshotId=crypto.randomUUID();const snapshot={combinationId:logicalOptionId,mealHead:input.mealHead,components:validated.components,nutrition:validated.nutrition,templateId:`TPL_${input.mealHead}`,templateVersion:'INDIA_COMMON_MEAL_TEMPLATES_V2',generatorVersion:'COMMON_FOOD_COMBINATION_ENGINE_V1',rankingVersion:'COMMON_FOOD_RANKING_V1',diversitySignature:canonicalHash(validated.components.map(x=>x.foodId).sort()).slice(0,24),preferenceScore:0,nutritionScore:0,overallScore:0,warnings:validated.nutrition.fibre===null?['FIBRE_NOT_REPORTED_NO_FIBRE_CLAIM']:[],shortages:[],optionHash:canonicalHash({logicalOptionId,version:(prior?.snapshotVersion??0)+1,validated}),snapshotVersion:(prior?.snapshotVersion??0)+1} satisfies CombinationSnapshot;try{await saveCombinationOption({id:snapshotId,logicalOptionId,supersedesId:null,planId,planVersionId:validated.planVersionId,expectedPlanVersionId:input.expectedPlanVersionId,mealHead:input.mealHead,snapshot});}catch(e){if((e as {code?:string}).code==='STALE_PLAN_VERSION')throw new CommonFoodApiError('STALE_PLAN_VERSION',409);throw e;}return snapshot;}

export const assertExactCommonFoodSelection=(options:Array<{optionId:string;mealHead:MealHead}>)=>{
 const invalidMeal=MEAL_HEADS.find(head=>options.filter(option=>option.mealHead===head).length!==5);
 if(options.length!==35||new Set(options.map(option=>option.optionId)).size!==35||invalidMeal)throw new CommonFoodApiError('INVALID_OPTION_SELECTION',422,'Exactly five distinct options must be selected for every meal.');
};

export async function replaceSelectedCommonFoodOptions(account:AuthenticatedAccount,clientId:string,planId:string,input:{expectedPlanVersionId:string;options:Array<{optionId:string;mealHead:MealHead;components:Array<{foodId:string;servingId:string;multiplier:number}>}>}){
 assertExactCommonFoodSelection(input.options);
 const snapshots:CombinationSnapshot[]=[];
 for(const option of input.options){const validated=await validateCommonFoodOption(account,clientId,planId,option);if(validated.planVersionId!==input.expectedPlanVersionId)throw new CommonFoodApiError('STALE_PLAN_VERSION',409);snapshots.push({combinationId:option.optionId,mealHead:option.mealHead,components:validated.components,nutrition:validated.nutrition,templateId:`TPL_${option.mealHead}`,templateVersion:'INDIA_COMMON_MEAL_TEMPLATES_V2',generatorVersion:'COMMON_FOOD_COMBINATION_ENGINE_V1',rankingVersion:'COMMON_FOOD_RANKING_V1',diversitySignature:canonicalHash(validated.components.map(item=>item.foodId).sort()).slice(0,24),preferenceScore:0,nutritionScore:0,overallScore:0,warnings:validated.nutrition.fibre===null?['FIBRE_NOT_REPORTED_NO_FIBRE_CLAIM']:[],shortages:[],optionHash:canonicalHash({optionId:option.optionId,validated}),snapshotVersion:1});}
 try{return {planVersionId:input.expectedPlanVersionId,options:await replaceCombinationOptionSelection({planId,planVersionId:input.expectedPlanVersionId,expectedPlanVersionId:input.expectedPlanVersionId,options:snapshots})};}catch(error){if((error as {code?:string}).code==='STALE_PLAN_VERSION')throw new CommonFoodApiError('STALE_PLAN_VERSION',409);throw error;}
}

export async function mutateCommonFoodOption(account:AuthenticatedAccount,clientId:string,planId:string,optionId:string,expectedPlanVersionId:string,mutator:(items:Array<{foodId:string;servingId:string;multiplier:number}>)=>Array<{foodId:string;servingId:string;multiplier:number}>){await resolveClientMealGenerationContext({account,clientId,planId});const old=await getCombinationOption(optionId,planId);if(!old)throw new CommonFoodApiError('OPTION_NOT_FOUND',404);const before=old.components.map(x=>({foodId:x.foodId,servingId:x.servingId,multiplier:x.multiplier})),after=mutator(before);if(after.length===before.length){const changed=after.map((x,i)=>[before[i],x] as const).filter(([a,b])=>a.foodId!==b.foodId);for(const [a,b] of changed){const oldFood=foods.find(f=>f.id===a.foodId),newFood=foods.find(f=>f.id===b.foodId);if(!oldFood||!newFood||ontologyFor(oldFood).primaryRole!==ontologyFor(newFood).primaryRole)throw new CommonFoodApiError('COMPONENT_ROLE_MISMATCH',422,'Replacement must preserve the structured meal component role.');}}return persistValidatedOption(account,clientId,planId,{optionId,expectedPlanVersionId,mealHead:old.mealHead,components:after});}
export async function autoBalanceCommonFoodOption(account:AuthenticatedAccount,clientId:string,planId:string,optionId:string,input:{expectedPlanVersionId:string;lockedFoodIds:string[]}){const resolved=await resolveClientMealGenerationContext({account,clientId,planId});const old=await getCombinationOption(optionId,planId);if(!old)throw new CommonFoodApiError('OPTION_NOT_FOUND',404);let current=old.components.map(x=>({foodId:x.foodId,servingId:x.servingId,multiplier:x.multiplier}));const target=resolved.mealTargets[old.mealHead];const distance=(n:{kcal:number|null;protein:number|null})=>Math.abs((n.kcal??target.kcal)-target.kcal)/Math.max(1,target.kcalTolerance)+Math.abs((n.protein??target.protein)-target.protein)/Math.max(1,target.proteinTolerance);let validated=validateManualCombination({foods,context:resolved.context,mealHead:old.mealHead,components:current,target});for(let index=0;index<current.length;index++){if(input.lockedFoodIds.includes(current[index].foodId))continue;const food=foods.find(f=>f.id===current[index].foodId),serving=food?.servings.find(s=>s.id===current[index].servingId);if(!serving)continue;let best=current[index],bestDistance=distance(validated.nutrition);for(const multiplier of serving.allowedMultipliers){const candidate=current.map((x,i)=>i===index?{...x,multiplier}:x);try{const result=validateManualCombination({foods,context:resolved.context,mealHead:old.mealHead,components:candidate,target});const quality=validateMealQuality({components:result.components,foods:new Map(foods.map(f=>[f.id,f])),mealHead:old.mealHead,nutrition:result.nutrition,target});const nextDistance=distance(result.nutrition);if(quality.eligible&&nextDistance<bestDistance){best=candidate[index];bestDistance=nextDistance;}}catch{continue;}}current=current.map((x,i)=>i===index?best:x);validated=validateManualCombination({foods,context:resolved.context,mealHead:old.mealHead,components:current,target});}return persistValidatedOption(account,clientId,planId,{optionId,expectedPlanVersionId:input.expectedPlanVersionId,mealHead:old.mealHead,components:current});}
export async function reloadCommonFoodOptions(account:AuthenticatedAccount,clientId:string,planId:string){const r=await resolveClientMealGenerationContext({account,clientId,planId});return {planVersionId:r.planVersion.id,options:(await listCombinationOptions(planId,r.planVersion.id)).filter(Boolean)};}
export const commonFoodCatalogue=foods;
